moka-rs/moka

.github/workflows/CI.yml
Cargo.toml
README.md
src/builder.rs
src/cache.rs
src/frequency_sketch.rs
src/lib.rs
src/segment.rs
src/thread_pool.rs

- Implement time-to-idle policy.
- Introduce the cache builder.
- Add more methods to `ConcurrentCache` trait: `capacity()`, `time_to_live()`, `time_to_idle()` and `num_segments()`
- Move `sync()` method to a separate `ConcurrentCacheExt` trait.
- Replace lazy_static with once_cell.
- Bump the version to 0.1.0-alpha.3.
- Raise the minimum supported Rust version (MSRV) to 1.45.2 (because of quanta crate).
- Stabilized a unit test for the frequency sketch by increase the capacity of the sketch.

Support time-to-idle policy

---

Cargo.toml
src/common.rs
src/common/deque.rs
src/common/deques.rs
src/lib.rs
src/sync.rs
src/sync/cache.rs

- Implement time-to-live policy.
- Bump the version to 0.1.0-beta.1
- Fixed bugs causing segmentation fault (use after free) when accessing stale deq node.

Support time-to-live policy

---

Cargo.toml
README.md
build.rs
src/common.rs
src/lib.rs
src/sync.rs
src/sync/builder.rs
src/sync/cache.rs
src/sync/segment.rs
tests/skeptic.rs

- Bumped the version to 0.1.0-beta.2
- Changed the cache API:
- Removed the `ConcurrentCache` trait.
- Renamed `remove()` method to `invalidate()`, and changed the return type to `()`.
- Changed the return type of `insert()` to `()`.
- Changed the return type of `get()` from `Arc<V>` to `V`. 
- Updated `get()` and `invalidate()` methods to accept the type for the key that implement the `Borrow` trait for `Arc<K>`.
- Updated the cache `Builder` to support the `initial_capacity`.
- Added doc tests (skeptic) to the README.
- Wrote some rustdoc.

Change the cache API

---

.circleci/config.yml
README.md

- Run `cargo tarpaulin --features future` at CircleCI.
- Publish the coverage report to Coveralls.

Enable an CI for test coverage

---

.vscode/settings.json
CHANGELOG.md
Cargo.toml
README.md
src/common.rs
src/common/deque.rs
src/future.rs
src/future/builder.rs
src/future/cache.rs
src/lib.rs
src/sync.rs
src/sync/base_cache.rs
src/sync/cache.rs
src/sync/deques.rs
src/sync/segment.rs
src/unsync.rs
src/unsync/builder.rs
src/unsync/cache.rs
src/unsync/deques.rs

This pull request adds the `invalidate_all` method to all `sync`, `future` and `unsync` caches. The `invalidate_all` method was requested in #10.
- Add `invalidate_all` method.
- Update internal `handle_upsert` and `evict` methods to prevent problems including segfault caused by race conditions between the sync/eviction thread and client writes (especially `invalidate`).
- Bump the version to 0.3.0.
- Upgrade a dependency: once_cell 1.5 -> 1.7.

Add the `invalidate_all` method to all caches

---

.github/workflows/CI.yml
Cargo.toml
README.md
src/lib.rs

Moka's minimum supported Rust version (MSRV) is currently 1.45.2. However, it does not compile anymore on 1.45.2 because the latest version of socket2 crate (0.4.0) requires Rust 1.46.0 or newer. 
Moka indirectly depends on socket2 via async-io or async-std crates:
1. Moka depends on async-io only when "future" feature is enabled.
- Therefore, we will raise the MSRV for future feature to 1.46.0.
2. Moka depends on async-std only for testing (a dev dependency).
- We want to keep the MSRV as 1.45.2 when no feature is enabled.
This PR does the followings:
- For 1 (MSRV 1.46.0 for future feature):
- Update a CI (GitHub Action) job for Rust 1.45.2 to skip a step with `cargo test --release --features future`.
- Add a CI job for Rust 1.46.0 to run the same step.
- For 2 (MSRV 1.45.2 for no …

Raise MSRV for "future" feature to 1.46.0

---

.github/workflows/CI.yml
Cargo.toml
build.rs
tests/skeptic.rs

This stops skeptic from having to be included in the build stage of all downstream users of this crate (which I'm currently getting because of [libunftp](https://crates.io/crates/libunftp) depending on this).
skeptic is a [pretty heavy crate](https://crates.io/crates/skeptic/0.13.6/dependencies), depending on other crates like `cargo_metadata`, `error_chain`, `pulldown_cmark` ecc. which in turn depend on a bunch of other stuff. This doesn't make sense to me, as tests for an external crates shouldn't be run by downstream users.
This PR makes it so skeptic tests are only run when compiling with the `RUSTFLAGS="--cfg skeptic"` flag

Stop skeptic from having to be compiled by all downstream users

---

CHANGELOG.md
src/future/builder.rs
src/future/cache.rs
src/sync/base_cache.rs
src/sync/builder.rs
src/sync/cache.rs
src/sync/segment.rs

This PR adds `Send`, `Sync` and `'static` bounds to the type parameters `K` (key), `V` (value) and `S` (hasher state) of the following cache implementations:
This will prevent the following usage from drawing undefined behavior:
- Single thread application using an above thread-safe cache.
- Store non-`Send` or non-`Sync` type (such as `std::rc::Rc`) as key (`K`) and/or (`Value`).
- Or, store non static reference type as key and/or value.
Until now, storing such key or value types was possible in _single thread_ application (including single-threaded async runtime such as Actix-rt) because above caches did not ask these bounds explicitly. 
However doing so is incorrect as it can draw undefined behavior. This is because these …

Add Send + Sync + 'static bounds to K, V and S of sync and future Caches

---

.vscode/settings.json
CHANGELOG.md
Cargo.toml
README.md
src/common.rs
src/common/deque.rs
src/common/error.rs
src/common/thread_pool.rs
src/future/builder.rs
src/future/cache.rs
src/lib.rs
src/sync.rs
src/sync/base_cache.rs
src/sync/builder.rs
src/sync/cache.rs
src/sync/housekeeper.rs
src/sync/invalidator.rs
src/sync/segment.rs
src/unsync/builder.rs
src/unsync/cache.rs

This PR adds the `invalidate_entries_if` method and supporting methods to all caches in Moka. `invalidate_entries_if` invalidates the entire cache based on a predicate on the key and value of each cache entry. This method was requested by #10.
- (API) Add `invalidate_entries_if` method to all cache implementations in Moka:
- `unsync::Cache`
- (API) Add `support_invalidation_closures` method to the following cache builders:
- `sync::CacheBuilder`
- `future::CacheBuilder`
- Note that for these `sync` and `future` caches, this method must be called at the cache creation time as the cache needs to maintain additional internal data structures to support `invalidate_entries_if` method. Otherwise, calling `invalidate_entries_if` will …

Add the `invalidate_entries_if` method

---

CHANGELOG.md
Cargo.toml
README.md
src/future.rs
src/future/cache.rs
src/future/value_initializer.rs
src/sync.rs
src/sync/base_cache.rs
src/sync/cache.rs
src/sync/segment.rs
src/sync/value_initializer.rs

This PR adds the `get_or_insert_with` and `get_or_try_insert_with` methods to `sync` and `future` caches in Moka. These methods ensure the key exists in the cache by inserting the return value from the given closure/future if the key does not exist. They also guarantee the closure/future is evaluated only once even if they are called from multiple threads/async tasks for the same key at the same time.
This feature was requested by #15.
- (API) Add `get_or_insert_with` and `get_or_try_insert_with` methods to the following cache implementations in Moka:
- Add internal `sync::value_initializer` and `future::value_initializer` modules, containing `cht::HashMap` for waiters.
----
Fixes #15

Add `get_or_insert_with` method

---

CHANGELOG.md
Cargo.toml
README.md
src/future/cache.rs
src/future/value_initializer.rs
src/lib.rs
src/sync/base_cache.rs
src/sync/cache.rs
src/sync/invalidator.rs
src/sync/segment.rs
src/sync/value_initializer.rs
src/unsync/cache.rs

- Replace cht v0.4.1, the concurrent hash table implementation, with a fork, [moka-cht][moka-cht] v0.5.0.
- Update `value_initializer` modules to replace moka-cht `HashMap` with `SegmentedHash` for better concurrency.
- Temporary allow [clippy::redundant_allocation][clippy-lint]. (A new lint in Clippy 0.1.54 beta).
- This will be addressed in Moka v0.6.0 as it requires changing the return type of `get_or_try_insert_with`.
[moka-cht]: https://github.com/moka-rs/moka-cht
[clippy-lint]: https://rust-lang.github.io/rust-clippy/master/index.html#redundant_allocation

Switch to moka-cht

---

CHANGELOG.md
Cargo.toml
README.md
src/future/cache.rs
src/future/value_initializer.rs
src/sync/cache.rs
src/sync/segment.rs
src/sync/value_initializer.rs

Change `get_or_try_insert_with` of `sync::{Cache, SegmentedCache}` and `future::Cache` to return a concrete error type rather than a trait object.
**Before** (`sync::Cache`)
```rust
pub fn get_or_try_insert_with<F>(&self, key: K, init: F) ->
Result<V, Arc<Box<dyn Error + Send + Sync + 'static>>>
where
F: FnOnce() -> Result<V, Box<dyn Error + Send + Sync + 'static>>
```
**After**
```rust
pub fn get_or_try_insert_with<F, E>(&self, key: K, init: F) -> Result<V, Arc<E>>
where
F: FnOnce() -> Result<V, E>,
E: Error + Send + Sync + 'static,
```
There is a subtle change in the behavior. `get_or_try_insert_with` used to guarantee that the closure `F` to evaluate once even if multiple threads call it at the same time on the same cache key.
Now this is not always true:
- Only one of the closures …

Change get_or_try_insert_with to return a concrete error type rather than a trait object

---

CHANGELOG.md
src/common/frequency_sketch.rs
src/sync/base_cache.rs
src/unsync/cache.rs

This PR fixes the issue #25, `usize` multiply overflow on big cache capacity.
- Removed the multiply operation (`max_capacity * 32`) when setting the capacity of the popularity estimator `FrequencySketch`.
- The implementation of the estimator was replaced in an older version of Moka and the multiply operation was not really needed since then.
- Added code to ensure that the capacity of the popularity estimator always fits within a range of `128u32..=u32::MAX`.
- Changed the type of the internal fields of the estimator from `usize` to `u32` so that the estimator will work consistency on any platform with different pointer width.
- Added unit tests to `sync::base_cache` and `unsync::cache` modules to ensure overflows should not happen and sizes of the population estimators are correct:
- …

Handle `usize` overflow on big cache capacity

---

.vscode/settings.json
CHANGELOG.md
Cargo.toml
src/future/cache.rs
src/future/value_initializer.rs
src/sync/cache.rs
src/sync/value_initializer.rs

- Add examples to the doc comments.
- Add reqwest crate to the dev-dependency because one of the examples uses it.
----
Fixes #29

Add examples to the doc for `get_or_insert_with` and `get_or_try_insert_with` methods

---

CHANGELOG.md
Cargo.toml
README.md

Downgrade crossbeam-epoch crate used in moka-cht crate from v0.9.x to v0.8.0. I am hoping this would workaround #34.
- Changed moka-cht version from v0.5.0 to **v0.4.2**.
- v0.5.0 has a dependency to crossbeam-epoch v0.9.x.
- **v0.4.2** has a dependency to crossbeam-epoch **v0.8.x**.

Downgrade crossbeam-epoch from v0.9.x to v0.8.x

---

tests/ui/future/try_get_with_non_send_future.rs
tests/ui/future/try_get_with_non_send_future.stderr
tests/ui/future/try_get_with_non_static_future.rs
tests/ui/future/try_get_with_non_static_future.stderr

When I created #32, I added UI tests (compile error tests) for `get_or_insert_with` method, but I forgot to add tests for `get_or_try_insert_with` method. This pull request adds these tests.

Add UI tests for `get_or_try_insert_with`

---

CHANGELOG.md
src/future/cache.rs
src/future/value_initializer.rs
src/sync/cache.rs
src/sync/value_initializer.rs

In #23, the trait bounds for `E` was changed from `Box<dyn Error + ...>` to `Error + ...`.
**Current**
```rust
use std::error::Error;
pub fn get_or_try_insert_with<F, E>(&self, key: K, init: F) -> Result<V, Arc<E>>
where
F: FnOnce() -> Result<V, E>,
E: Error + Send + Sync + 'static,
```
This pull request removes the `Error` bound from `E`.
**After**
```rust
pub fn get_or_try_insert_with<F, E>(&self, key: K, init: F) -> Result<V, Arc<E>>
where
F: FnOnce() -> Result<V, E>,
E: Send + Sync + 'static,
```
We are doing this because having `Error` is not necessary and too strict. For example, the following code will not compile with the current bounds, because `anyhow::Error` does not implement `std::error::Error` trait.
```rust
// Cargo.toml
// [dependencies]
// anyhow = "1"
use …
```

Remove the `Error` bound from `get_or_try_insert_with` method

---

.github/workflows/CI.yml
.vscode/settings.json
CHANGELOG.md
Cargo.toml
README.md
src/common.rs
src/common/thread_pool.rs
src/common/time_compat.rs
src/common/time_quanta.rs
src/future/cache.rs
src/lib.rs
src/sync.rs
src/sync/base_cache.rs
src/sync/cache.rs
src/sync/invalidator.rs
src/sync/segment.rs
src/unsync.rs
src/unsync/cache.rs

This pull request is for supporting Linux on 32-bit MIPS and ARMv5TE. These platforms does not provide `std::sync::atomic::AtomicU64` so currently both Moka and quanta will not compile.
~~After merging this PR, Moka will compile on 32-bit MIPS. For ARMv5TE, you need to add `default-features = false` to "moka" dependency in Cargo.toml and then Moka will compile.~~
After this PR is merged, you can resolve the errors by disabling the default features by adding `default-features = false` to the dependency declaration in Cargo.toml. This will remove quanta from the dependencies and enable a fall-back implementation in Moka.
- Add a cargo feature ~~`quanta`~~ `atomic64` and make it a default feature.
- Add a module `common::time` and conditionally choose the source file from "time_quanta.rs" or …

Support Linux on MIPS and ARMv5TE

---

.github/workflows/LinuxCrossCompileTest.yml
src/common/thread_pool.rs

Add a CI (GitHub Actions) using [rust-embedded/cross](https://github.com/rust-embedded/cross). It does the followings:
1. Cross-compile Moka to a specified Linux target.
2. Run `cross test`(similar to `cargo test` but without integration tests) using QEMU user space emulation.
Currently, the following targets are tested:
- `aarch64-unknown-linux-musl`
- `i686-unknown-linux-musl`
- `armv7-unknown-linux-musleabihf`
- `armv5te-unknown-linux-musleabi`
- `mips-unknown-linux-musl`
- `mipsel-unknown-linux-musl`
There is one concern though. [The README of cross](https://github.com/rust-embedded/cross#supported-targets) says: 
> `cross test` runs units tests sequentially because QEMU gets upset when you spawn multiple threads. This means that, if one of your unit tests spawns threads, then it's …

CI: Add cross-compile tests for some Linux targets

---

.github/workflows/CI.yml
.github/workflows/LinuxCrossCompileTest.yml
.vscode/settings.json
CHANGELOG.md
Cargo.toml
README.md
src/common.rs
src/common/thread_pool.rs
src/common/time_atomic64.rs
src/common/time_compat.rs
src/future/cache.rs
src/lib.rs
src/sync.rs
src/sync/base_cache.rs
src/sync/cache.rs
src/sync/invalidator.rs
src/sync/segment.rs
src/unsync.rs
src/unsync/cache.rs

This PR includes changes from the following PRs: #39, #40, #42 and #44.

Merge recent changes from maint-0.5 branch into master

---

CHANGELOG.md
Cargo.toml
src/future/cache.rs
src/future/value_initializer.rs
src/sync/cache.rs
src/sync/value_initializer.rs

This PR addresses the issue reported by #43.
When the user-provided `init` future/closure for `get_or_insert_with` or `get_or_try_insert_with` method has panicked, it will catch the panic, remove the waiter for the key, and resume the panic. It also restarts other in-progress (actually blocked) method calls on the same key.
- Add `futures` crate for Moka's `future` feature.
- Update `future::Cache` to handle panic in the `init` future of `get_or_insert_with` and `get_or_try_insert_with`.
- Update `sync::Cache` to handle panic in the `init` future of `get_or_insert_with` and `get_or_try_insert_with`.
- Add unit tests.
----
Fixes #43

Handle panic in the `init` closure/future of `get_or_insert_with` and `get_or_try_insert_with`

---

src/future/cache.rs
src/sync/cache.rs
src/sync/deques.rs
src/sync/segment.rs

Disable Clippy on Rust 1.58 beta until we figure out what to do on the following lint:
https://rust-lang.github.io/rust-clippy/master/index.html#non_send_fields_in_send_ty
Relates to #54

Temporary disable Clippy on Rust 1.58 beta on CI

---

.vscode/settings.json
Cargo.toml
README.md
src/lib.rs

- Add "Moka in Production" section to the README.
- Remove references to Ristretto from the doc. It turned out Moka is mostly taking design idea from Caffeine and very little from Ristretto.

Update readme 2021 12

---

README.md
src/common.rs
src/common/builder_utils.rs
src/future/builder.rs
src/lib.rs
src/sync/builder.rs
src/unsync/builder.rs

This is a follow up PR for #56.
- Update `CacheBuilder::build_with_hasher` method to do the same duration checks to `build` methods.
- Update the API doc to explain panics.
- Not related to overflow checks but also tweaked the contents of the README.

Protect overflow when computing expiration (part 2)

---

CHANGELOG.md
Cargo.toml
src/future/cache.rs
src/future/value_initializer.rs
src/sync/value_initializer.rs

This PR addresses the issue described in #59. So `get_or_insert_with` and `get_or_try_insert_with` methods in `future::Cache` will no longer panic if previous inserting task was aborted.
- Add `WaiterGuard` to the value initializer used by these methods and it will ensure to remove the waiter (a lock) when enclosing async task is aborted.
- Add unit test cases for the issue.
Fixes #59.

Prevent `future::get_or_*_insert_with` to panic after inserting task was aborted

---

CHANGELOG.md
README.md
src/common.rs
src/common/frequency_sketch.rs
src/future/builder.rs
src/future/cache.rs
src/sync/base_cache.rs
src/sync/builder.rs
src/sync/cache.rs
src/sync/segment.rs
src/unsync/builder.rs
src/unsync/cache.rs

This is a follow-up PR for #24.
This PR makes these caches not to initialize the LFU filter (`FrequencySketch`) at the cache creation time, but initialize and enable it once the cache is half full (based on the weighted size).
The size of the `FrequencySketch` is determined by the followings:
- If the `weigher` is set, use the current number of the entries in the cache.
- If not, use the `max_capacity` of the cache, which is equals to the max number of entries.
This PR also changes the `max_capacity` from `usize` to `u64`.

Lazily initialize and enable the LFU filter

---

README.md

Update the README:
- Add a link to a wiki page in this repository, explaining TinyLFU/W-TinyLFU policies and showing benchmark results (hit ratios).
I used Caffeine's simulator for the benchmarks. I wrote a simple JNI-based driver for Moka. I am planning to open-source it in a separate git repository under this moka-rs organization.

Update the README: Add a link to the page with Moka's cache policies and benchmark results

---

.github/workflows/Miri.yml
src/common/deque.rs
src/sync/deques.rs
src/unsync/deques.rs

This PR addresses the memory leak issue reported by #64.
The memory leak happens when evicting/expiring an entry or manually invalidating an entry. It should not happen when dropping a cache.
The leaking data is the key of an entry, last modified timestamp (`u64`) and last accessed timestamp (`u64`). It does not include the value of an entry.
- This issue can be reproduced by the code in the description of #64.
- Or by running the following commands. [Miri](https://github.com/rust-lang/miri) will detect similar issue in `Deque`'s unit tests:
```console
$ rustup update nightly
$ rustup +nightly component add miri
$ cargo +nightly miri test deque
```
```
running 4 tests
test common::deque::tests::basics ... ok
test common::deque::tests::drop ... ok
test common::deque::tests::iter ... ok …
```

Fix memory leak when evicting or expiring an entry (v0.7.x)

---

.github/workflows/Miri.yml
src/common/deque.rs
src/sync/deques.rs
src/unsync/deques.rs

This is the to #65 but for Moka v0.6.x.
Relates to #64.

Fix memory leak when evicting or expiring an entry (v0.6.x)

---

Cargo.toml

This PR update `Cargo.toml` for switching the minimum version of crossbeam-channel from v0.5.0 to v0.5.2.
v0.5.2 addressed some stacked borrow violations found by Miri so it will be safer to depend on that version (or newer versions):
- https://github.com/crossbeam-rs/crossbeam/blob/master/crossbeam-channel/CHANGELOG.md#version-052

Update the minimum version of crossbeam-channel from v0.5.0 to v0.5.2

---

src/future/builder.rs
src/sync/builder.rs
src/sync/housekeeper.rs
src/unsync/builder.rs

Fix Clippy warnings.
- clippy 0.1.59 (7c0b2509239 2022-01-13)

Fix Clippy 1.59 warnings for Moka v0.7.x

---

src/common/deque.rs
src/sync/segment.rs

This adds a number of clippy related fixes:
- [needless_borrow](https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow)
- [clone_on_copy](https://rust-lang.github.io/rust-clippy/master/index.html#clone_on_copy)
- [erasing_op](https://rust-lang.github.io/rust-clippy/master/index.html#erasing_op)
Tested using: `cargo clippy --lib --tests --all-features --all-targets -- -D warnings`
If you run that command you'll notice there are still two errors that are thrown, both instances of [needless_collect](https://rust-lang.github.io/rust-clippy/master/index.html#needless_collect). This could be a false positive. I wasn't sure after reviewing so I decided it was best to leave it as is.

Adds misc clippy fixes

---

src/sync/base_cache.rs
src/unsync/cache.rs

Moka v0.7.0 introduced size-aware cache management. However, there is a bug in the logic to estimate the number of keys that the frequency sketch (the LFU filter) would manage, and can create oversized sketch up to two times bigger than necessary. This bug exists only for size-aware cache management.
This PR fixes the bug by trying not to increase the sketch size once estimated.
* * *

Fix a bug that can create oversized frequency sketch when weigher is set

---

src/sync.rs
src/sync/base_cache.rs
src/sync/entry_info.rs

- To reduce memory utilization, change `EntryInfo` from `enum` to `struct`. (See #72)
- Remove `ValueEntryBuilder` and `CacheFeatures`. We used them to select an enum variant of `EntryInfo`.
* * *

Change `EntryInfo` from `enum` to `struct` to reduce memory utilization

---

.vscode/settings.json
Cargo.toml
README.md
src/cht.rs
src/cht/map.rs
src/cht/map/bucket.rs
src/cht/map/bucket_array_ref.rs
src/cht/segment.rs
src/cht/segment/map.rs
src/cht/test_util.rs
src/cht/test_util/tests.rs
src/future/value_initializer.rs
src/lib.rs
src/sync/base_cache.rs
src/sync/value_initializer.rs

This PR adds source files imported from moka-cht crate.
-  Add source files (modules) used by Moka (as `moka::cht::*` modules).
- Remove moka-cht crate from the dependency.
- Add crossbeam-epoch v0.8.2 to the dependency.
- Update the existing `use` statement in Moka modules to refer to `moka::cht::SegmentedHashMap`.
- Change visibility of `moka::cht::*` modules from public to crate public.
- Remove unused feature `num_cpu` from `moka::cht::*` modules.
- Temporary disable unit tests for `cht::*` modules.
- Update and re-enable unit tests for `moka::cht::*` modules.
- Update the doc.

Import cht source files for better integration

---

src/cht/map/bucket.rs
src/cht/map/bucket_array_ref.rs

- Perform GC-only rehashing to remove tombstones.
- Shrink capacity when possible.
* * *

Reduce memory overhead in the cht

---

.vscode/settings.json
Cargo.toml
src/future/value_initializer.rs
src/sync.rs
src/sync/base_cache.rs
src/sync/deques.rs
src/sync/invalidator.rs
src/sync/value_initializer.rs

- Replace `Arc` for `Arc<ValueEntry>`, `Arc<EntryInfo>` and `Arc<value_initializer::Waiter>`.
- Add `triomphe` to the dependencies.
Note: Did not replace `Arc` for `Arc<K>` as this change leaks to the public APIs. e.g. `get(&Q)`.
* * *

Replace some `std::sync::Arc` with `triomphe::Arc` to reduce memory utilization

---

.vscode/settings.json
Cargo.toml
src/cht/map/bucket.rs
src/cht/segment/map.rs
src/common/deque.rs
src/common/frequency_sketch.rs
src/future/cache.rs
src/lib.rs
src/sync.rs
src/sync/base_cache.rs
src/sync/debug_counters.rs
src/sync/entry_info.rs

When this feature is enabled:
- `moka::GlobalDebugCounters::current` function is provided.
- `moka::future::Cache::debug_stats` method is provided.
- The eviction batch size is changed to 10,000.
* * *

Add unstable-debug-counters feature

---

src/cht/segment/map.rs

I misunderstood what the initial capacity would do for `cht::SegmentedHashMap`.  I thought it was the initial capacity of the entire hash map, but the cht author meant it was the initial capacity of each segment in the hash map. Since Moka uses `SegmentedHashMap` with currently hard-coded number of segments `64`, setting the initial capacity using Moka's `CacheBuilder` results the hash map 64 times bigger than desired.
This PR changes the initial capacity of `moka::cht::SegmentedHashMap` to be the capacity of the entire hash map.

Fix a wrong (oversized) initial capacity for the internal hash map

---

.github/workflows/CI.yml
.vscode/settings.json
Cargo.toml
README.md
src/common.rs
src/common/deque.rs
src/sync.rs
src/sync/base_cache.rs
src/sync/deques.rs
src/unsync.rs
src/unsync/cache.rs
src/unsync/deques.rs

- Raise the minimum supported Rust version (MSRV) to 1.51.0.
- Add tagptr crate to the dependencies.
- Remove `region: CacheRegion` field from `DeqNode`.
- Change the pointer type used in `access_order_q_node` field of `DeqNodes` from `NonNull<DeqNode<T>>` to `TagNonNull<DeqNome<T>, 2>`, and embed `CacheRegion` value into the 2-bit tag space of the pointer.
- Update the methods in `Deques` to handle the `TagNonNull` pointers.
* * *

Embed CacheRegion value into a TagNonNull pointer 

---

.cargo/config
.vscode/settings.json
src/cht.rs
src/cht/segment/map.rs
src/cht/test_util.rs
src/cht/test_util/tests.rs

Enable cht tests

---

CHANGELOG.md
Cargo.toml
README.md
src/future/cache.rs
src/lib.rs
src/sync/base_cache.rs
src/sync/cache.rs

- Remove authors field from Cargo.toml:
- https://rust-lang.github.io/rfcs/3052-optional-authors-field.html

Prepare for v0.7.2

---

src/cht/segment.rs
src/future/cache.rs
src/future/value_initializer.rs
src/sync.rs
src/sync/base_cache.rs
src/sync/cache.rs
src/sync/invalidator.rs
src/sync/segment.rs
src/sync/value_initializer.rs

Update crate-internal `cht` methods to take a hash value of the key so that they do not have to recalculate the hash from the key.

Avoid to calculate the same hash twice in `get`, `insert`, `invalidate`, etc. methods

---

CHANGELOG.md
Cargo.toml

crossbeam-channel v0.5.4 has a workaround for a bug in upstream (`rustc` or LLVM?) related to TLS access on AArch64 Linux: https://github.com/crossbeam-rs/crossbeam/pull/802
Ensure that Moka uses crossbeam-channel v0.5.4 or newer v0.5.x.

Update the minimum depending version of crossbeam-channel to v0.5.4

---

.circleci/config.yml
.github/workflows/CI.yml
.github/workflows/LinuxCrossCompileTest.yml
.github/workflows/Skeptic.yml
.vscode/settings.json
CHANGELOG.md
Cargo.toml
README.md
src/dash.rs
src/dash/base_cache.rs
src/dash/builder.rs
src/dash/cache.rs
src/future.rs
src/future/cache.rs
src/lib.rs
src/sync.rs
src/sync/cache.rs
src/unsync.rs
src/unsync/cache.rs

Add an optional cache implementation `moka::dash::Cache`, which uses the `dashmap::DashMap` as the internal storage. The `moka::dash::Cache` provides similar (but less) APIs to `moka::sync::Cache`.
To use this optional cache, add "dash" feature for the moka dependency in Cargo.toml.
* * *
Fixes #92

Add `moka::dash::Cache`, which uses `dash::DashMap` as the internal storage

---

CHANGELOG.md
Cargo.toml
src/dash.rs
src/dash/base_cache.rs
src/dash/cache.rs
src/dash/iter.rs
src/dash/mapref.rs
src/lib.rs

This PR adds `iter` method to the `moka::dash::Cache`. This method returns an iterator of the cache, whose `next` method will return a reference to an entries in the cache.
* * *
Fixes #93

Iterator for `dash::Cache`

---

.github/workflows/CI.yml
Cargo.toml

Need to raise the version to avoid compile errors with old lib and rand crates.

Raise the minimum depending version of skeptic to v0.13.5

---

CHANGELOG.md
README.md
src/dash/base_cache.rs
src/dash/builder.rs
src/dash/cache.rs
src/future.rs
src/future/builder.rs
src/future/cache.rs
src/future/value_initializer.rs
src/lib.rs
src/policy.rs
src/sync/base_cache.rs
src/sync/builder.rs
src/sync/cache.rs
src/sync/segment.rs
src/unsync/builder.rs
src/unsync/cache.rs

Rename the following cache methods, and make the methods with old names deprecated:
- `get_or_insert_with(K, F)` → `get_with(K, F)`
- `get_or_try_insert_with(K, F)` → `try_get_with(K, F)`
Add `policy()` method to caches returning a cache `Policy` struct. Move the following cache methods to it:
- `max_capacity()` → `policy().max_capacity()`
- `num_segments()` → `policy().num_segments()`
- `time_to_live()` → `policy().time_to_live()`
- `time_to_idle()` → `policy().time_to_idle()`
Add `blocking()` method to `future::Cache` returning a `BlockingOp` struct. Move the following cache methods to it:
- `blocking_insert(K, V)` → `blocking().insert(K, V)`
- `blocking_invalidate(K, V)` → `blocking().invalidate(K, V)`

API stabilization: Smaller core cache API, prefer shorter names for common methods

---

.circleci/config.yml
.vscode/settings.json
src/dash/base_cache.rs
src/sync/base_cache.rs
src/unsync/cache.rs

Update the Circle CI job for Cargo Tarpaulin.
- Disable some test cases in `test_skt_capacity_will_not_overflow` to avoid out of memory error.
- Upgrade the Circle CI Ubuntu VM image to the latest version.
* * *
Fixes #108

CI: Fix the code coverage job

---

CHANGELOG.md
src/cht/map/bucket_array_ref.rs
src/cht/segment.rs
src/dash/base_cache.rs
src/dash/cache.rs
src/future/cache.rs
src/sync/base_cache.rs
src/sync/cache.rs
src/sync/segment.rs
src/unsync/cache.rs

This PR adds a `contains_key` method to all cache implementations:
- `dash::Cache`
- `unsync::Cache`
This method checks if a key is present in the cache. It does not reset the idle timer or update the historic popularity estimator.
* * *
Fixes #107

Add `contains_key` method to all cache implementations

---

Cargo.toml

Disable the default-features for [Triomphe crate](https://crates.io/crates/triomphe) to remove`serde` and `stable_deref_trait` crates from the dependency. (https://github.com/Manishearth/triomphe/pull/5)
**Before**
```console
$ cargo tree --all-features --target x86_64-unknown-linux-gnu
├── triomphe v0.1.5
│   ├── memoffset v0.6.5
│   │   [build-dependencies]
│   │   └── autocfg v1.1.0
│   ├── serde v1.0.136
│   │   └── serde_derive v1.0.136 (proc-macro)
│   │       ├── proc-macro2 v1.0.37 (*)
│   │       ├── quote v1.0.17 (*)
│   │       └── syn v1.0.91 (*)
│   └── stable_deref_trait v1.2.0
```
**After**
```console
├── triomphe v0.1.5
│   └── memoffset v0.6.5
│       [build-dependencies]
│       └── autocfg v1.1.0
```

Disable the default features for Triomphe crate

---

CHANGELOG.md
Cargo.toml
src/cht/map/bucket.rs
src/cht/map/bucket_array_ref.rs
src/cht/segment.rs
src/dash/cache.rs
src/future/cache.rs
src/sync.rs
src/sync/base_cache.rs
src/sync/cache.rs
src/sync/iter.rs
src/sync/segment.rs
src/unsync.rs
src/unsync/cache.rs
src/unsync/iter.rs

This PR adds iterator visiting all key-value pairs in arbitrary order.
- Add the `iter` method, who returns an iterator, to the following caches:
- Not-thread-safe cache:
- `unsync::Cache`
- Concurrent Caches:
- Implement `IntoIterator` to all the caches including experimental `dash::Cache`.
Fixes #112
The `unsync::Cache` employs `std::collections::HashMap` as the central key-value storage:
- The iterator element type is `(&K, &V)`.
- No mutation on the cache is allowed while an iterator is alive.
- Mutations includes both read operations like `get` and write operations like `insert`.
These concurrent caches employ `moka::cht::SegmentedHashMap` as the central key-value storage:
- The iterator element type is `(std::sync::Arc<K>, …

Add `iter` method to create an iterator to `unsync`, `sync` and `future` caches

---

CHANGELOG.md
src/dash/base_cache.rs
src/dash/cache.rs
src/dash/iter.rs
src/lib.rs

This PR fixes a bug that the `dash::Cache` iterator can return expired entries.
- Now the `next` method of `dash::Cache` iterator checks whether next entry is expired or not and skip it when expired.
- Update the unit test cases to detect this bug.

Fix the `dash::Cache` iterator not to return expired entries

---

CHANGELOG.md
README.md

Also add the Table of Contents to the README.

Update the README and CHANGELOG about opting out Quanta

---

CHANGELOG.md
src/future/cache.rs
src/sync/cache.rs
src/sync/segment.rs

This adds `get_with_if` method requested by #123 to the following caches:
* * *
Fixes #123

Add `get_with_if` method to `sync` and `future` caches

---

Cargo.toml
src/common/unsafe_weak_pointer.rs
src/sync/housekeeper.rs
src/sync/invalidator.rs

This transmute from a `Weak<T>` to a `usize` is shockingly common in both the ecosystem and the standard library. It's doubly bad because `Weak<T>` is a `repr(Rust)` type, so without manually inspecting its layout at runtime it is a mistake to assume it has any particular layout. But primarily, this is a round-trip of a pointer through an integer type via transmute, and it's pretty clear Rust cannot have a sound memory model that permits these alongside the usual suite of compiler optimizations (casts are different, they're annoying but possible to support).
If you're looking for other examples of this approach, `rayon` does a very similar thing to get pointers between threads: https://github.com/rayon-rs/rayon/blob/5b6adbbf5c6944ec42b54530820ee8c0ad0e35a9/src/lib.rs#L123-L147

Remove ptr-int transmute by converting UnsafeWeakPointer from usize to *mut T

---

CHANGELOG.md
Cargo.toml
README.md
src/common/time.rs
src/common/time/atomic_time.rs

Upgrade quanta crate from v0.9.x to v0.10.0. It has the fix for #119.
* * *
Fixes #119

Upgrade quanta to v0.10.0

---

.github/workflows/Skeptic.yml
CHANGELOG.md
Cargo.toml
src/dash/cache.rs
src/future/cache.rs
src/lib.rs
src/sync/cache.rs
tests/compile_tests/dash/clone/dash_cache_clone.rs
tests/compile_tests/dash/clone/dash_cache_clone.stderr
tests/compile_tests/default/clone/sync_cache_clone.rs
tests/compile_tests/default/clone/sync_cache_clone.stderr
tests/compile_tests/default/clone/sync_seg_cache_clone.rs
tests/compile_tests/default/clone/sync_seg_cache_clone.stderr
tests/compile_tests/future/clone/future_cache_clone.rs
tests/compile_tests/future/clone/future_cache_clone.stderr

Remove unnecessary `K: Clone` bound from the following caches when they are `Clone`:
- `dash::Cache`
* * *
Fixes #131

Remove unnecessary `K: Clone` bound from some caches when they are `Clone`

---

src/future/cache.rs
src/sync/cache.rs
src/sync/segment.rs
src/unsync/cache.rs

- `unsync::Cache`
Note that `dash::Cache` already has `Debug` impl.
* * * 
Fixes #132

Add `Debug` impl to the following caches

---

.github/workflows/CI.yml
.github/workflows/CIQuantaDisabled.yml

- To avoid compile errors when testing MSRV (1.51.0), run the following commands for MSRV CI to pin the versions of indexmap and native-tls crates:
- `cargo update -p indexmap --precise 1.8.2`
- `cargo update -p native-tls --precise 0.2.8`
- Run `cargo tree --features 'future, dash'` on the main CI.

Fix the CI for MSRV by pinning the versions of indexmap and native-tls

---

.github/workflows/CI.yml
.github/workflows/CIQuantaDisabled.yml
Cargo.toml
tests/runtime_actix_rt2.rs
tests/runtime_async_std.rs
tests/runtime_tokio.rs

The all async integration tests under the tests folder were not running as they were ignored by the test runner. Fix the issue by correcting the attributes on the modules and functions.

Fix async integration tests

---

README.md
src/future/cache.rs

Doc: Fix broken links to `future::Cache::blocking` in the README and rustdoc

---

.github/workflows/Audit.yml
.github/workflows/CI.yml
.github/workflows/CIQuantaDisabled.yml
Cargo.toml

- Enable Cargo Audit on the CI
- Raise the minimum version for reqwest (dev dependency) to v0.11.11 to avoid the following Hyper issues
- https://rustsec.org/advisories/RUSTSEC-2021-0078
- https://rustsec.org/advisories/RUSTSEC-2021-0079
- https://rustsec.org/advisories/RUSTSEC-2021-0020

Enable Cargo Audit on the CI

---

CHANGELOG.md
src/common/concurrent.rs
src/common/concurrent/atomic_time/atomic_time.rs
src/common/concurrent/atomic_time/atomic_time_compat.rs
src/common/concurrent/entry_info.rs
src/dash/base_cache.rs
src/dash/cache.rs
src/future/cache.rs
src/sync/cache.rs
src/sync/segment.rs
src/sync_base/base_cache.rs

Up to Moka v0.8.5, cache entry's `last_modified` and `last_accessed` timestamps were not set to the current time when it was inserted (when it was [temporary admitted](https://github.com/moka-rs/moka/wiki#tinylfu-current-version-of-moka)). Instead, they were set to the time when the entry was admitted. This is done by the housekeeper thread with ~0.3 second interval when cache is not receiving heavy writes. 
This caused an issue #155 that `invalidate_all` and `invalidate_entries_if` methods will not invalidate entries that were inserted just before `invalidate_all` or `invalidate_entries_if` was called.
This PR fixes the issue by setting cache entry's `last_modified` and `last_accessed` timestamps to the time when it was inserted:
- `EntryInfo`'s timestamps will be set when it is …

Set entry's timestamps immediately after insertion

---

src/common/concurrent/entry_info.rs
src/dash/base_cache.rs
src/sync_base/base_cache.rs
src/unsync/cache.rs

- Update `check_struct_size` of `EntryInfo` struct as the size of the struct changed in Rust 1.62 for 32 bit platforms.
- `EntryInfo` on some 32 bit platform has a field with `RwLock`.
- Fix Clippy warnings. (Clippy beta 0.1.63, 6c1f1428998 2022-06-28)

Fix CI failures for Rust 1.62 and Clippy beta 0.1.63

---

.github/workflows/CI.yml
.github/workflows/CIQuantaDisabled.yml
Cargo.toml

This PR adds `logging` feature, which enables optional dependency to `log` crate. (This feature will be used by the eviction listener #145)

Add `logging` feature to enable optional `log` crate dependency

---

src/sync/cache.rs

It was using the queued mode which was incorrect.

Fix the doc example for eviction listener with the immediate mode

---

.vscode/settings.json
CHANGELOG.md
Cargo.toml
src/cht/map/bucket.rs
src/cht/map/bucket_array_ref.rs
src/cht/segment.rs
src/future/cache.rs
src/future/value_initializer.rs
src/sync/cache.rs
src/sync/segment.rs
src/sync/value_initializer.rs
src/sync_base/base_cache.rs
src/sync_base/invalidator.rs
src/sync_base/key_lock.rs

This PR changes the trait bound `Arc<K>: Borrow<Q>` to `K: Borrow<Q>` for the following methods of `sync` and `future` caches.
- `contains_key`
- `get`
- `invalidate`
This fixes #163 for `sync` and `future` caches. Now their methods will accept `&[u8]` as the key `&Q` when `K` is `Vec<u8>`.

Change the trait bound `Arc<K>: Borrow<Q>` to `K: Borrow<Q>` (`sync` and `future` caches)

---

CHANGELOG.md
Cargo.toml
src/cht/map/bucket.rs
src/cht/map/bucket_array_ref.rs

(Rewritten on July 19, 2022)
Prevent segmentation fault (use-after-free) in `sync` and `future` caches. (Fixes #34):
- It was caused by race-conditions when many threads are concurrently rehashing (extending or shrinking) an internal hash table `moka::cht`:
- Although the creator of the original `cht` designed the rehashing to work fine in such situation, it is not working as expected.
- To fix it, add a lock to the rehash function to ensure only one thread can participate rehashing at a time.
- To prevent potential inconsistency issues in non x86 based systems, strengthen the memory ordering used for `compare_exchange_weak`.
- Before: `Ordering::Release`, meaning read: relaxed, write: release.
- After: `Ordering::AcqRel`, meaning read: acquire, write: release.
Upgrade crossbeam-epoch …

Prevent segmentation fault in `sync` and `future` caches, and also upgrade crossbeam-epoch to v0.9.9

---

src/common/concurrent/entry_info.rs

Fix a test `entry_info::check_struct_size` for macOS. Also skip it on non-Linux or non-macOS platforms.

Fix a test `entry_info::check_struct_size` for macOS

---

.github/workflows/CI.yml
.github/workflows/CIQuantaDisabled.yml
CHANGELOG.md
Cargo.toml
src/common/builder_utils.rs
src/common/concurrent/housekeeper.rs
src/common/concurrent/thread_pool.rs
src/dash/base_cache.rs
src/dash/cache.rs
src/future/builder.rs
src/future/cache.rs
src/sync/builder.rs
src/sync/cache.rs
src/sync/segment.rs
src/sync_base/base_cache.rs

- Add `thread_pool_enabled` method with a `bool` parameter to `sync::CacheBuilder`.
- If called with `false`, it will disable the thread pool for the housekeeper for the cache being built.
- Rename current thread-pool based `Housekeeper` to `ThreadPoolHousekeeper`.
- Add `BlockingHousekeeper`.

Optionally disable thread pools in `sync::Cache`

---

Cargo.toml

With regards to the closed https://github.com/moka-rs/moka/pull/172
This is the best solution I have been able to come up with.  I will give this example to cargo developers.  In the meantime, the way to address this would be to migrate `getrandom` from `dev-dependencies` to regular `dependencies`.  It will be eliminated away by the compiler and linker as it is not used anyways.  In the meantime it allows one to use `js` feature.
Once again, to clarify, `js` features is needed for wasm but you can not specify sub-crate features for `dev-dependencies` as in release mode cargo errors out with `no such dependency found for feature 'js'`...  
I've tried using `js = ["getrandom?/js"]` syntax, but optional dependencies (`?`) are available only on the nightly channel and that would require to …

Address multi-platform issues with getrandom dependency

---

Cargo.toml

Move `getrandom` back to under the dev-dependencies.
Fixes the unit test broken by #173.

Follow up the `js` feature

---

CHANGELOG.md
Cargo.toml
src/cht/segment.rs

Fixes #176 
When a `sync` or `future` cache was dropped, value part of cache entries were left allocated (leaked). This was due to a bug in the `Drop::drop` method of `moka::cht::SegmentedHashMap`; it was using `bucket::defer_acquire_destroy` function to drop any entry (a `bucket` struct), but that function only drops the key part of the entry.
Fixed the bug by updating the `drop` method of `moka::cht::SegmentedCache` to use the followings:
* For a live `bucket` (having both the key and value), use `bucket::defer_destroy_bucket` function to drop both the key and value.
* For a dead `bucket` (having the tombstone bit set and having only the key), continue using `bucket::defer_acquire_destroy` function to drop only the key.
Verified the fix by the following methods:
- Ran the [reproducing …

Fix memory leak when dropping a `sync` or `future` cache.

---

.cirrus.yml
.gitignore

This PR adds Cirrus CI job to run Linux AArch64 tests on real hardware.

CI: Run Linux AArch64 tests on real hardware using Cirrus CI

---

.cirrus.yml
.github/workflows/CI.yml
.github/workflows/CIQuantaDisabled.yml

once_cell v1.15.0 or newer requires Rust 2021 edition, which is not supported by the MSRV.

CI: Pin once_cell to v1.14.0 for the MSRV

---

src/future.rs
src/future/cache.rs
src/future/value_initializer.rs
src/sync.rs
src/sync/cache.rs
src/sync/segment.rs
src/sync/value_initializer.rs

This is the inital PR for issue #184 
I was thinking to use TypeId with `()` type for the Error type when return `InitResult`, but not sure if this will have some conflict with other parts of the code as I saw `()` is use somewhere else. So I created internal structure `OptionallyNone` to represent this error type. 
I also noticing the guarantee of call once only if the init closure return `Ok/Some`. If it returns `Err/None`, it is not gurantee to have once call. I think this definitely make sense, perhaps it is good to update the docummentation? Thanks
Let me know if there's any comments or suggestions. Thanks

Add new api `optionally_get_with`

---

CHANGELOG.md
Cargo.toml

- Bump the version to v0.9.5.
[v0.9.5](https://github.com/moka-rs/moka/milestone/27) will have more items later and we will update the change log again (via a separate pull request).

Prepare for v0.9.5 release (part 1)

---

src/future/cache.rs
src/sync/cache.rs
src/sync/segment.rs

Related issue #185 
Add "by_ref" version of api for "get_with", "get_with_if", "try_get_with", "optionally_get_with"

Add 'by_ref' api

---

src/cht/segment.rs
src/dash/base_cache.rs
src/sync_base/base_cache.rs
src/unsync/cache.rs

clippy 0.1.66 (e080cc5a659 2022-11-01)

Fix Clippy warnings (Rust 1.66 beta)

---

Cargo.toml
src/future/cache.rs
src/future/value_initializer.rs
src/sync/cache.rs
src/sync/value_initializer.rs
src/sync_base/base_cache.rs
tests/entry_api_actix_rt2.rs
tests/entry_api_async_std.rs
tests/entry_api_sync.rs
tests/entry_api_tokio.rs

In the current implementation (up to v0.9.5), there is a small chance that the following methods to evaluate the `init` closure/function more than once in concurrent calls:
- `get_with`
- `get_with_if`
- `optionally_get_with`
- `try_get_with`
It will happen when a call to one of these methods is made when another call to the same method on the same key is about to complete.
New test cases in he following files will reproduce the issue:
- `tests/entry_api_sync.rs`
- `tests/entry_api_tokio.rs`
- `tests/entry_api_actix_rt2.rs`
- `tests/entry_api_async_std.rs`
This PR fixes the issue by doing a double check if the value still does not exist after the lock is acquired and also extending the lock as needed.

Prevent race condition in `get_with` method to avoid evaluating `init` closure/future multiple times

---

src/common.rs
src/common/concurrent/thread_pool.rs
src/common/entry.rs
src/future.rs
src/future/cache.rs
src/future/entry_selector.rs
src/lib.rs
src/sync.rs
src/sync/cache.rs
src/sync/entry_selector.rs
src/sync/segment.rs
src/sync_base/base_cache.rs
tests/entry_api_actix_rt2.rs
tests/entry_api_async_std.rs
tests/entry_api_sync.rs
tests/entry_api_tokio.rs

Add `entry` and `entry_by_ref` APIs to `sync` and `future` caches. They return a struct `OwnedKeyEntrySelector` or `RefKeyEntrySelector` respectively. You can use their methods like `or_insert` to select or insert an entry of a cache.
These methods on the entry selectors return an `Entry`, a snapshot of key and value, carrying additional information `is_fresh` to indicates if the value was freshly computed or cached.
```rust
use moka::sync::Cache;
let cache: Cache<String, u32> = Cache::new(100);
let key = "key1".to_string();
let entry = cache.entry_by_ref(&key).or_insert(3);
assert!(entry.is_fresh());
assert_eq!(entry.key(), &key);
assert_eq!(entry.into_value(), 3);
let entry = cache.entry(key).or_insert(6);
// Not fresh because the value was already in the cache. …
```

Add the "entry" and "entry_by_ref" APIs

---

.circleci/config.yml
.cirrus.yml
.github/workflows/CI.yml
src/sync/cache.rs

Hope this PR fixes the flaky tests on GitHub Actions.
- Make the following tests in the `sync::cache` ignored by default and run separately in GitHub Actions:
- `test_key_lock_used_by_immediate_removal_notifications`
- `drop_value_immediately_after_eviction`
- Show CPU info on GitHub Actions and CircleCI

Fix flaky tests on GitHub Actions

---

src/future/cache.rs
src/sync/cache.rs

They were deprecated since v0.8.0 (March 23rd, 2022).

Remove deprecated APIs `get_or_insert_with` and `get_or_try_insert_with`

---

.cirrus.yml
.github/workflows/CI.yml
.github/workflows/CIQuantaDisabled.yml

When testing the MSRV, downgrade `reqwest` to v0.11.12, otherwise we cannot downgrade `native-tls` to v0.2.8.

Fix the CI for MSRV 1.51

---

.cirrus.yml
.github/workflows/CI.yml
.github/workflows/CIQuantaDisabled.yml

When testing minimal dependency versions, upgrade `openssl` to v0.10.39, otherwise building `openssl-sys` will fail on Linux.

Fix the CI for Rust nightly with minimal dependency versions

---

src/sync/builder.rs

This PR fixes #207 by coping values of some fields in the cache builder struct.

Fix the bug that setting number of segments of sync cache will disable notifications

---

.cirrus.yml
.github/workflows/CI.yml
.github/workflows/CIQuantaDisabled.yml
Cargo.toml
README.md
src/cht/segment.rs
src/dash/cache.rs
src/future/builder.rs
src/future/cache.rs
src/sync/builder.rs
src/sync/cache.rs
src/unsync/cache.rs

This is a documentation update. It adds examples to cache builder's `build_with_hasher`. It will make it clear that user should specify the type of `S` explicitly. (`Cache<K, V, S>` instead of `Cache<K, V>`).
* * *
Fixes #214.

doc: Add examples for `build_with_hasher` method of cache builders

---

src/future/cache.rs
src/future/entry_selector.rs
src/sync/cache.rs
src/sync/entry_selector.rs

This PR updates the test cases and documentation for entry's `is_fresh` method, to verify and clarify the guarantees for call coalescing. 
**Test Cases**
Update test cases to verify the return value of `is_fresh` method:
**Documentation**
Update the documentation to clarify `is_fresh`'s guarantee for call coalescing.
* * *
Fixes #217.

Update test cases and documentation for entry's `is_fresh` method

---

CHANGELOG.md
Cargo.toml

- Bump the version to v0.9.7.
Note: The future inflation issue is not has been addressed. Will open another PR for it.

Prepare for v0.9.7 release

---

src/future.rs
src/future/cache.rs
src/future/value_initializer.rs

This PR will mitigate #212 for upcoming Moka v0.9.7 release.
`future::Cache`:
1. To mitigate current `rustc`'s optimization issue, switched the internally using type for the `init` future from `impl Future` to a reference `Pin<&mut impl Future>`.
2. Eliminated an internal async function `ValueInitializer:init_or_read(..., init, ...)` from the call path.
`future::Cache`:

Reduce the size of the future returned by async `get_with` and friend methods (v0.9)

---

src/future.rs
src/future/cache.rs
src/future/entry_selector.rs
src/future/value_initializer.rs

This PR will mitigate #212 for upcoming Moka v0.10.0 release.
This PR does the same thing to PR #222, but on the `master` branch instead of the `maint-09` branch.
`future::Cache`:
1. To mitigate current `rustc`'s optimization issue, switched the internally using type for the `init` future from `impl Future` to a reference `Pin<&mut impl Future>`.
2. Eliminated an internal async function `ValueInitializer:init_or_read(..., init, ...)` from the call path.
`future::Cache`:

Reduce the size of the future returned by async `get_with` and friend methods (v0.10)

---

src/future/cache.rs
src/future/value_initializer.rs
src/sync.rs
src/sync/cache.rs
src/sync/value_initializer.rs

Refactor an internal module `sync::value_initializer` to match the new structure of `future::value_initializer` introduced by #220.
- Eliminated an internal method `ValueInitializer:init_or_read(..., init, ...)` from the call path.
Also remove unnecessary `Arc::clone`s from both `sync::Cache` and `future::Cache`.

Refactor an internal module `sync::value_initializer`

---

README.md

- Update the info about `quick_cache` to `v0.2`.
- Add a comment to `moka` that the background threads will be removed from `v0.11`.
CC: @arthurprs

Update the feature comparison table in the README

---

.circleci/config.yml
.cirrus.yml

To fix #233, skip CI jobs on Circle CI and Cirrus CI if the branch is a temporary branch for GitHub merge queue.

Do not run external CI on temporary branches for GitHub merge queue

---

CHANGELOG.md
Cargo.toml
src/future/cache.rs
src/sync/cache.rs
src/sync/segment.rs
src/sync_base/base_cache.rs

To fix #230, make the cache implementations to store nothing when the max capacity is set to 0.
When the max capacity is set to 0, cache will do the followings:
- Create the internal concurrent hash map with initial capacity of 0.
- Do not enable the frequency sketch.
- Make the following methods to do nothing and return immediately:
- internal `insert_with_hash`
- internal `do_get_with_hash`
- external `sync`
Also added unit test called `max_capacity_zero`.
- command: `RUSTFLAGS='--cfg skeptic --cfg trybuild' cargo test -F future`

Do not cache anything when max capacity is zero

---

Cargo.toml
src/common/concurrent/thread_pool.rs

- Replace the deprecated `ScheduledThreadPool::with_name` method with the recommended `builder` method.
- Since the `builder` method was just added to v0.2.7, had to change the minimum version of scheduled-thread-pool from v0.2.6 to v0.2.7.

Avoid a deprecation warning from scheduled-thread-pool v0.2.7

---

.cirrus.yml
.github/workflows/CI.yml
.github/workflows/CIQuantaDisabled.yml

- When testing minimal dependency versions, upgrade `cc` to v1.0.61, otherwise building `openssl-sys` will fail on Linux.
- When testing MSRV 1.51.0, downgrade `thiserror` and `serde` to v1.0.39 and v1.0.156
respectively.

Fix the CI for MSRV and Rust nightly (cc, thiserror, serde)

---

CHANGELOG.md
src/future/cache.rs

Fixes #242.
- Fix an internal `do_blocking_invalidate` method to notify the eviction listener when an entry is evicted.
- Update a test to verify that the eviction listener is notified when an entry is evicted by `.blocking().invalidate(key)`.

`future::Cache`'s `.blocking().invalidate(key)` should trigger the eviction listener

---

.cirrus.yml
.github/workflows/CI.yml
.github/workflows/CIQuantaDisabled.yml
CHANGELOG.md
Cargo.toml
README.md
src/lib.rs

Fixes #252
- Bump the MSRV from 1.51 to 1.60 (2022-04-07).
- Bump the `moka` version to v0.10.2.

Bump the MSRV to 1.60 (2022-04-07)

---

CHANGELOG.md
Cargo.toml

Fixes #243
This `quanta` version depends on `mach2` crate for macOS/iOS targets as a replacement of unmaintained `mach`.

Upgrade `quanta` to v0.11.0

---

CHANGELOG.md
README.md
src/future/cache.rs
src/sync/cache.rs
src/sync/segment.rs

This PR adds the `remove` method to `future` and `sync` caches. It does the same to the `invalidate` method except returning a _clone_ of the value that has been discarded.
```rust
// moka::future::Cache
/// Discards any cached value for the key and returns a _clone_ of the value.
///
/// If you do not need to get the value that has been discarded, use the
/// [`invalidate`](#method.invalidate) method instead.
///
/// The key may be any borrowed form of the cache's key type, but `Hash` and `Eq`
/// on the borrowed form _must_ match those for the key type.
pub async fn remove<Q>(&self, key: &Q) -> Option<V>
where
K: Borrow<Q>,
Q: Hash + Eq + ?Sized;
// FYI, an existing `invalidate` method.
pub async fn invalidate<Q>(&self, key: &Q)
where
K: Borrow<Q>,
Q: Hash + Eq + ?Sized,
```
Fixes #255.

Add the `remove` method

---

CHANGELOG.md
src/common/concurrent/deques.rs
src/common/deque.rs
src/common/timer_wheel.rs
src/sync_base/base_cache.rs

I found bugs in the `sync` and `future` caches; they were mutating an internal deque node through a `NonNull` pointer derived from a shared ref `&`. This PR fixes these bugs.
These bugs already existed from very early version of Moka but I could not find them until now. [Miri](https://github.com/rust-lang/miri) tests could have helped to find them, but we are not running Miri tests on the `sync_base` module who has the bugs. This is because the module uses some FFI calls that Miri does not support.
In commit https://github.com/moka-rs/moka/commit/03c75ff0ae7d39fc21f8d206ca0103ec59bbc7fb (included in this PR), I added a test to `deque` module to reproduce the bug and confirmed that Miri can catch it.
```console
$ cargo +nightly miri test deque
test …
```

Fix the caches mutating a deque node through a `NonNull` pointer derived from a shared reference

---

Cargo.toml
README.md
src/common/deque.rs
src/future/builder.rs
src/future/cache.rs
src/lib.rs
src/policy.rs
src/sync/builder.rs
src/sync/cache.rs
src/sync_base/base_cache.rs

This PR adds more rustdoc and unit tests for per-entry expiration #248.

Per-entry expiration. (Add more doc and tests)

---

.github/workflows/Miri.yml

To workaround the issue described by #269, use a specific version of Rust nightly for Miri test for now. We are going to use `nightly-2023-05-24`.
We will revert this change when the original issue is addressed.

CI: Workaround a CI failure for Miri test by using a specific version of Rust nightly

---

CHANGELOG.md
Cargo.toml
examples/eviction_listener.rs
examples/size_aware_eviction.rs

- Bump the Moka version to v0.11.1.
- Reorder some cache operations in the `eviction_listener` example and add some comments.
- Apply `cargo fmt`.

Tweak some examples

---

.github/workflows/Kani.yml
CHANGELOG.md
src/common/frequency_sketch.rs

Fixes #267.
Fixes #113.
This PR prevents an internal `index_of` method of `FrequencySketch` from panicking by arithmetic overflow.
- Only debug build was affected by this issue.
- Release build was not affected unless overflow checks were explicitly enabled at the build time.
- Replace an `u64` addition (`+`) operator in `FrequencySketch::index_of` method with `wrapping_add` method.
- Wrapping (modular) addition is the desired behavior for `index_of` method.
- The `+` operator will behave the same to `wrapping _add` method in release build (where overflow checks are disabled).
- Add test harnesses (test cases) for [Kani Verifier](https://github.com/model-checking/kani) to ensure there is no chance for arithmetic overflows and other panics to occur in `FrequencySketch` (not only for …

Fix occasional panic in `FrequencySketch` in debug build

---

.github/workflows/Miri.yml
src/cht/map/bucket.rs
src/common/concurrent/housekeeper.rs
src/common/deque.rs
src/sync/builder.rs
src/sync_base/invalidator.rs

- Revert "Workaround a CI failure for Miri test by using a specific version"
- Fixes #269
- Fix Clippy warnings.
- clippy 0.1.71 (eff24c06d8f 2023-05-29)

CI: Fix CI errors 2023-06

---

.cirrus.yml
.github/workflows/CI.yml
.github/workflows/CIQuantaDisabled.yml
CHANGELOG.md
Cargo.toml
README.md
src/lib.rs

Change the MSRV from 1.60 to 1.65. Rust 1.65 was released on Nov 3, 2022, seven months ago.
We need Rust 1.65 for the followings:
- #257
- `std::thread::available_parallelism()` requires 1.64 in order to work reliably on some Linux platforms.
- We can remove `num_cpus` crate.
- #265
- Not mandatory, but it uses `if let — else`, which was introduced in 1.65.
Also this PR bumps the `moka` version to v0.11.2.

Bump the minimum supported Rust version (MSRV) to 1.65 (Nov 3, 2022)

---

CHANGELOG.md
Cargo.toml
src/cht/segment.rs
src/common.rs
src/common/concurrent/thread_pool.rs

This PR replaces `num_cpus::get()` with `std::thread::available_concurrency()` introduced in Rust 1.59.0. (Fixes #257)
NOTE: `available_concurrency()` requires Rust 1.64.0 or newer to work reliably in some Linux container environment. See the descriptions of #257.

Remove `num_cpus` crate from the dependency

---

src/cht/map/bucket.rs

This tries to reduce compile times and slightly improve the code by avoiding theclosure-based `probe_loop` fn and related control flow types/matches. Instead this uses an Iterator with a special `reload` flag.
Its another attempt to slightly improve upon https://github.com/moka-rs/moka/issues/203.
As a testcase, I used https://github.com/getsentry/symbolicator, and here is the difference in output of `cargo llvm-lines -p symbolicator-service`:
before:
```
Lines                  Copies               Function name
-----                  ------               -------------
2460076                63753                (TOTAL)
44782 (1.8%,  8.8%)    298 (0.5%,  2.3%)  moka::cht::map::bucket::BucketArray<K,V>::probe_loop
15704 (0.6%, 21.2%)    151 (0.2%,  7.6%) …
```

Remove `probe_loop` in favor of Iterator

---

CHANGELOG.md
src/cht/map/bucket.rs

Follows up #265.
Update the change log and source code comments.

Follow up #265

---

.cirrus.yml
.github/workflows/CI.yml
.github/workflows/CIQuantaDisabled.yml
CHANGELOG.md
Cargo.toml
README.md
src/cht/map/bucket.rs
src/common/concurrent/housekeeper.rs
src/common/concurrent/thread_pool.rs
src/common/deque.rs
src/lib.rs
src/sync/builder.rs
src/sync_base/invalidator.rs

Back-port miscellaneous changes from v0.10.x and v0.11.x.
- Bump the minimum supported Rust version (MSRV) to 1.60 (Apr 7, 2022).
- This is because `quanta` v0.11.0 requires it.
- Upgrade `quanta` to v0.11.0 to resolve [RUSTSEC-2020-0168: mach is unmaintained](https://github.com/moka-rs/moka/issues/243).
- See #251 for Moka v0.10.2.
- Update the minimum version of `scheduled-thread-pool` to v0.2.7 and replace an usage of a deprecated function.
- See #241 for Moka v0.10.1.
- Disable some Cirrus CI jobs.
- See #276 for Moka v0.11.2.
Fix Clippy warnings.

Misc back-port to v0.9.x branch

---

CHANGELOG.md
README.md
src/common/deque.rs
src/dash/base_cache.rs
src/sync_base/base_cache.rs
src/unsync/cache.rs

Back-port the following fix to v0.9.8:
- #259 (for v0.11.0)

Backport #259 to v0.9.8

---

.cirrus.yml
src/cht/map/bucket.rs
src/common/concurrent/housekeeper.rs
src/common/deque.rs
src/sync/builder.rs
src/sync_base/invalidator.rs

- Fix Clippy warnings.
- Disable some Cirrus CI jobs.
- See #276 for Moka v0.11.2.

Misc changes for v0.10.x

---

.github/workflows/Lints.yml
src/cht/segment.rs
src/common/frequency_sketch.rs
src/notification/notifier.rs
src/sync/cache.rs
src/sync/segment.rs
src/sync_base/base_cache.rs
src/sync_base/invalidator.rs

- Fix Clippy warnings.
- clippy 0.1.72 (a47f796a365 2023-07-22)
- Add a cfg flag called `clippy_beta` to allow a lint when Clippy beta is used.
- This is needed because the same lint is not available in Clippy stable.

Fix Clippy warnings for v0.11.x

---

.ci_extras/pin-crate-vers-msrv.sh
.ci_extras/pin-crate-vers-nightly.sh
.cirrus.yml
.github/workflows/CI.yml
.github/workflows/CIQuantaDisabled.yml
.github/workflows/Lints.yml
Cargo.toml
src/cht/segment.rs
src/common/frequency_sketch.rs
src/notification/notifier.rs
src/sync/cache.rs
src/sync/segment.rs
src/sync_base/invalidator.rs

- clippy 0.1.72 (a47f796a365 2023-07-22)
- Add a cfg flag called `clippy_beta` to allow a lint when Clippy beta is used.
- This is needed because the same lint is not available in Clippy stable.
- When testing the MSRV (1.60.0) of `moka` 0.10.x, downgrade `tempfile` to v3.6.0 so it will compile.

Fix Cilppy warnings and MSRV CI for v0.10.x

---

.ci_extras/pin-crate-vers-msrv.sh
.ci_extras/pin-crate-vers-nightly.sh
.cirrus.yml
.github/workflows/CI.yml
.github/workflows/CIQuantaDisabled.yml
.github/workflows/Lints.yml
src/cht/segment.rs
src/common/frequency_sketch.rs
src/notification/notifier.rs
src/sync/cache.rs
src/sync/segment.rs
src/sync_base/invalidator.rs

- clippy 0.1.72 (a47f796a365 2023-07-22)
- Add a cfg flag called `clippy_beta` to allow a lint when Clippy beta is used.
- This is needed because the same lint is not available in Clippy stable.
When testing the MSRV (1.60.0) of `moka` 0.10.x, downgrade the following crates, so they will compile:
- Downgrade `dashmap` to v5.4.0
- Downgrade `tempfile` to v3.6.0.

Fix Cilppy warnings and MSRV CI for v0.9.x

---

CHANGELOG.md
Cargo.toml
README.md
src/future/cache.rs
src/sync/cache.rs
src/sync/segment.rs
src/sync_base/base_cache.rs
src/sync_base/key_lock.rs

This PR fixes a bug in `sync::Cache` and `sync::SegmentedCache`, which causes eviction listener's key-level locks not to be removed after sending notifications. This happened only when the `Immediate` notification delivery mode is used for the eviction listener. (It is the default mode)  Another mode, `Queued` mode, is unaffected as it does not use the key locks.
These key locks are stored in an internal `moka::cht::SegmentedHashMap` with `Arc<K>` as their keys. So this bug caused the `SegmentedHashMap` to hold all keys `K` that has been inserted to the cache. It will continuously increasing memory usage until the cache is dropped.
Tested the fix by adding a check to unit test if the `SegmentedHashMap` is empty after sending all notifications.

Fix a bug in sync caches where memory usage kept increasing when the eviction listener is set (v0.9.x)

---

CHANGELOG.md
Cargo.toml
README.md
src/future/cache.rs
src/sync/cache.rs
src/sync/segment.rs
src/sync_base/base_cache.rs
src/sync_base/key_lock.rs

This PR fixes a bug in `sync::Cache` and `sync::SegmentedCache`, which causes eviction listener's key-level locks not to be removed after sending notifications. This happened only when the `Immediate` notification delivery mode is used for the eviction listener. (It is the default mode)  Another mode, `Queued` mode, is unaffected as it does not use the key locks.
These key locks are stored in an internal `moka::cht::SegmentedHashMap` with `Arc<K>` as their keys. So this bug caused the `SegmentedHashMap` to hold all keys `K` that has been inserted to the cache. It will continuously increasing memory usage until the cache is dropped.
Tested the fix by adding a check to unit test if the `SegmentedHashMap` is empty after sending all notifications.

Fix a bug in sync caches where memory usage kept increasing when the eviction listener is set (v0.11.x)

---

.ci_extras/pin-crate-vers-msrv.sh

When testing the MSRV 1.60, downgrade `tokio` to v1.29.1, otherwise it will not compile.

Fix the CI for MSRV 1.60 for v0.9.x

---

src/future/base_cache.rs
src/future/cache.rs
src/sync/cache.rs
src/sync_base/base_cache.rs

https://github.com/moka-rs/moka/pull/294#issuecomment-1687337263
> I was reviewing the codes and found that cache write operations (such as `insert` and `get_with`) may not record a write operation log if the caller (enclosing future) has been cancelled. This will leave a newly inserted cached entry not managed by the cache policies (LFU filter, LRU queue, etc.). When this happens, the entry will never be evicted by the policy, while it can be read by `get`, replaced by other `insert`, or removed by `invalidate`.
>
> This issue already existed in very early version of moka. But v0.12.0 will increase the chance of this issue to happen as it now supports for calling user supplied async eviction listener.
>
> A common solution for this would be write-ahead-log, which to record the write op …

Improve async cancellation safety of `future::Cache` (v0.12.0-beta.X)

---

src/cht/map/bucket.rs
src/notification/notifier.rs
src/sync_base/invalidator.rs

- Apply rustfmt for `if let ... else`.
- Remove allow `clippy::arc_with_non_send_sync` as the false positives are fixed in Clippy.

rustfmt and clippy (v0.12.x)

---

Cargo.toml
README.md

When publishing v0.12.0-beta.2, which made a crate feature `sync` disabled by default, I forgot to add the `sync` feature to the docs.rs metadata in `Cargo.toml`. As a result, [the doc for v0.12.0-beta.2](https://docs.rs/moka/0.12.0-beta.2/moka/index.html) was generated without the `sync` module (`sync::Cache`, etc).
This PR fixes it by adding the `sync` feature to the doc.rs metadata. It also updates the README.md.

Reenable the `sync` feature for doc.rs

---

Cargo.toml
src/future.rs
src/future/base_cache.rs
src/future/cache.rs

This PR replaces the async `may_yield` function introduced at `v0.12.0-beta.1` with a more efficient implementation. It uses an `async_lock::RwLock` between a user async task, that is currently running internal `do_run_pending_tasks`, and other user async tasks.
This will be more CPU efficient than `may_yield` because it makes some of the user async tasks to wait for reader locks, rather than keeping spinning, so that the async runtime scheduler can run other async tasks if there are any.
This PR also bumps the version to `v0.12.0-beta.3`.

Better async waiting for when the write op channel is full

---

CHANGELOG.md
src/future/base_cache.rs
src/policy.rs
src/sync_base/base_cache.rs

- Fixes #322
- Update the `Expiry` documentation for clarity.
This is for the `main` branch (v0.12.0). I will back-port this to the branch for v0.11.0.

Get the last modified time for upsert after acquiring key level lock

---

CHANGELOG.md
Cargo.toml
README.md
src/future/base_cache.rs
src/sync/cache.rs
src/sync_base/base_cache.rs

- Removed `-beta.N` from the version `v0.12.0`.
- Removed an internal field `invalidator_enabled` from `sync::base_cache::Inner`.
- Added some source code comments (`TODO` comments).

Prepare for v0.12.0 release

---

CHANGELOG.md
Cargo.toml
src/future/base_cache.rs
src/future/value_initializer.rs
src/sync/value_initializer.rs
src/sync_base/base_cache.rs

This PR fixes #329, a bug introduced to v0.12.0 causing memory leak in `get_with()`, `entry().or_insert_with()` and friend methods in `future::Cache`.
It also bumps the crate version to v0.12.1.
The bug was introduced by PR #294 for v0.12.0 ([src/future/value_initializer.rs diff L316-L330](https://github.com/moka-rs/moka/pull/294/files#diff-3df6f2ad1c01aeaaff49319246d71a65d7fd5ac8ae5bcd0c32a912ba38228f65L316-L330)). So this PR basically reverts the change.
Here are some backgrounds. An instance of `future::Cache` has a few internal concurrent hash tables (cht), and the following tables are related to this bug:
1. The main cht called `cache` map, which stores cached entries.
2. A cht called `waiter` map, which stores per-key reader-writer locks used by `get_with` and friends methods.
The …

Fix memory leak in `get_with` and friend methods of `future::Cache`

---

.github/workflows/LinuxCrossCompileTest.yml

Update Linux cross compile tests (linux-cross) on the `main` branch (for v0.12.x).
- Disable fail-fast strategy for linux-cross.
- Stop using actions-rs GH actions in linux-cross:
- Stop using `actions-rs/toolchain` and `actions-rs/cargo`.
- Start to use `dtolnay/rust-toolchain` and `taiki-e/install-action`.
- Upgrade `actions/checkout` from v2 to v4.
Note that the following tests are failing due to a Rust compiler/LLVM bug for MIPS targets. (See #333)
- linux-cross (mips-unknown-linux-musl)
- linux-cross (mipsel-unknown-linux-musl)

CI: Update Linux cross compile tests (v0.12.x)

---

.github/workflows/LinuxCrossCompileTest.yml
src/cht/map/bucket.rs
src/common/concurrent/entry_info.rs
src/notification/notifier.rs
src/sync_base/invalidator.rs

Update Linux cross compile tests (linux-cross) on the `v0.11.x` branch.
- To workaround [#333](https://github.com/moka-rs/moka/issues/333), pin the Rust version to 1.72.1 for the following tests:
- linux-cross (mips-unknown-linux-musl)
- linux-cross (mipsel-unknown-linux-musl)
- Disable fail-fast strategy for linux-cross.
- Stop using actions-rs GH actions in linux-cross:
- Stop using `actions-rs/toolchain` and `actions-rs/cargo`.
- Start to use `dtolnay/rust-toolchain` and `taiki-e/install-action`.
- Upgrade `actions/checkout` from v2 to v4.
- Apply rustfmt.
- Disable a Clippy lint `clippy::option_env_unwrap` in a test.
- Remove workarounds for a Clippy issue ([#301](https://github.com/moka-rs/moka/issues/301)):
- Remove allow `clippy::arc_with_non_send_sync` as the false positives have …

CI: Update Linux cross compile tests (v0.11.x)

---

.ci_extras/pin-crate-vers-msrv.sh
.github/workflows/LinuxCrossCompileTest.yml
src/common/concurrent/entry_info.rs
src/notification/notifier.rs
src/sync_base/invalidator.rs

Update Linux cross compile tests (linux-cross) on the `v0.10.x` branch.
- To workaround [#333](https://github.com/moka-rs/moka/issues/333), pin the Rust version to 1.72.1 for the following tests:
- linux-cross (mips-unknown-linux-musl)
- linux-cross (mipsel-unknown-linux-musl)
- Disable fail-fast strategy for linux-cross.
- Add more crates to downgrade when testing the MSRV (1.60.0):
- `async-executor` v1.5.1
- `reqwest` v0.11.18
- `regex` v1.9.6
- `memchr` v2.6.2
- `h2` v0.3.20
- `actix-rt` v2.8.0
- Stop using actions-rs GH actions in linux-cross:
- Stop using `actions-rs/toolchain` and `actions-rs/cargo`.
- Start to use `dtolnay/rust-toolchain` and `taiki-e/install-action`.
- Upgrade `actions/checkout` from v2 to v4.
- Apply rustfmt.
- Disable a Clippy lint `clippy::option_env_unwrap` …

CI: Update Linux cross compile tests (v0.10.x)

---

Cargo.toml
src/common/timer_wheel.rs
tests/compile_tests/default/clone/sync_cache_clone.stderr
tests/compile_tests/default/clone/sync_seg_cache_clone.stderr
tests/compile_tests/future/clone/future_cache_clone.stderr

* Move to edition 2021, and remove redundant `use` in test
* run tests with `TRYBUILD=overwrite`

Update to 2021 edition, bless tests

---

MIGRATION-GUIDE.md
README.md
examples/async_example.rs
examples/eviction_listener.rs
examples/sync_example.rs
src/cht/map/bucket.rs
src/common.rs
src/common/concurrent/deques.rs
src/common/concurrent/entry_info.rs
src/common/timer_wheel.rs
src/future/base_cache.rs
src/future/cache.rs
src/future/notifier.rs
src/future/value_initializer.rs
src/notification/notifier.rs
src/sync/cache.rs
src/sync/segment.rs
src/sync/value_initializer.rs
src/sync_base/base_cache.rs
tests/entry_api_actix_rt2.rs
tests/entry_api_async_std.rs
tests/entry_api_sync.rs
tests/entry_api_tokio.rs
tests/runtime_actix_rt2.rs
tests/runtime_async_std.rs
tests/runtime_tokio.rs

Makes the code a bit easier to read. Plus a few unneeded commas.
Some of these require migration to 2021 edition first (another PR)

Inline format args

---

src/cht/map/bucket.rs
src/cht/segment.rs
src/common.rs
src/common/concurrent.rs
src/common/concurrent/deques.rs
src/common/concurrent/entry_info.rs
src/common/concurrent/housekeeper.rs
src/common/deque.rs
src/common/time.rs
src/common/timer_wheel.rs
src/future.rs
src/future/base_cache.rs
src/future/builder.rs
src/future/cache.rs
src/future/housekeeper.rs
src/future/invalidator.rs
src/future/value_initializer.rs
src/sync/builder.rs
src/sync/cache.rs
src/sync/segment.rs
src/sync/value_initializer.rs
src/sync_base/base_cache.rs
src/sync_base/invalidator.rs

Most of these seemed reasonable, but feel free to push back on any of them. Clippy also recommended removing a few unused `&self`, but maybe will do that in a separate PR

A few clippy-suggested lints

---

.ci_extras/pin-crate-vers-msrv.sh
.ci_extras/pin-crate-vers-nightly.sh
.github/workflows/CI.yml
.github/workflows/CIQuantaDisabled.yml
Cargo.toml

Change the following dev dependencies:
- Raise the minimal `async-std` version from 1.1 to 1.2.
- Use `rustls` in `reqwest` instead of `native-tls` (openssl on Linux).

Fix the CI with minimal crate versions. (moka v0.12.x)

---

.ci_extras/pin-crate-vers-msrv.sh
.ci_extras/pin-crate-vers-nightly.sh
.github/workflows/CI.yml
.github/workflows/CIQuantaDisabled.yml
Cargo.toml

Change the following dev dependencies:
- Raise the minimal `async-std` version from 1.1 to 1.2.
- Use `rustls` in `reqwest` instead of `native-tls` (openssl on Linux).

Fix the CI with minimal crate versions. (moka v0.11.x)

---

.ci_extras/pin-crate-vers-nightly.sh
.github/workflows/CI.yml
.github/workflows/CIQuantaDisabled.yml

- Change the following dev dependencies:
- Change proc-macro2 from v1.0.60 to v1.0.63.
- Disable fail-fast feature on CI and CIQuantaDisabled workflows

 Fix the CI with minimal crate versions. (moka v0.11.x)

---

CHANGELOG.md
Cargo.toml
MIGRATION-GUIDE.md
README.md
src/common.rs
src/common/concurrent.rs
src/common/concurrent/deques.rs
src/common/concurrent/entry_info.rs
src/future/base_cache.rs
src/future/cache.rs
src/sync/cache.rs
src/sync_base/base_cache.rs

Fixes #345.
This pull request (PR) prevents timing issues in writes that cause inconsistencies between the cache's internal data structures such as the concurrent hash table and access-order queue.
The following new test case reproduces this issue in `v0.12.0` and `v0.12.1`:
- [`test_race_between_updating_entry_and_processing_its_write_op`](https://github.com/moka-rs/moka/pull/348/files#diff-338f772312880199137f8bbb508f15dd7f83457565cc983b85043cddd71b2f24)
1. Create a `Cache` with `max_capacity = 2` and `time_to_idle = 1 second`.
2. Insert key `a`.
3. Insert key `b`.
4. Insert key `c`.
- → When pending tasks are processed (at step 6), `c` will be evicted as the cache is full.
5. Pause for 2 seconds.
- → When pending tasks are processed (at step 6), `a` and `b` should expire.
6. Insert key …

Prevent timing issues causing inconsistencies between concurrent hash table and policy data structures

---

src/common/concurrent.rs
src/future/base_cache.rs
src/future/cache.rs
src/sync/cache.rs
src/sync_base/base_cache.rs

Fixes #359.
~~(We will merge this into the `main` branch after #348 is merged)~~
When a cached entry is read (by e.g. the `get` method) or write (by e.g. the `insert` method), the `last_accessed` time of the entry is updated. When `time_to_idle` of the `Cache` is set, the `last_accessed` time is used to determine whether the entry is expired or not.
Up to Moka `v0.12.1`, `last_accessed` time was _eventual consistent_ for read operations. So it will not be updated immediately after read, but will be updated sometime later when pending tasks are processed. (Note: It will be updated to the time when read was performed, not to the time when pending task is processed). This was designed so to achieve better throughput as updating `last_accessed` has a small performance overhead from a …

Update the access time of a cached entry immediately after the entry is read

---

Cargo.toml
examples/cascading_drop_async.rs
examples/eviction_listener.rs

As the eviction listener [cannot guarantee](https://github.com/moka-rs/moka/discussions/344#discussioncomment-7571847) that all references are dropped in time, it is a better idea to use the Drop trait of the cached items for some cases. A web-server may require to hold both a session cache and a (logged-in or related) users tree/map. Also added ttl variable for consistency, and modified sync() comment.

Example for cascading drop triggered by eviction

---

examples/cascading_drop_async.rs

As we discussed in https://github.com/moka-rs/moka/pull/350#issuecomment-1870995237, we will reduce the TTL value in the example from 3 secs to 2.5 secs.
Also this fixes a Clippy warning from a recent beta Clippy `0.1.75 (1a06ac5b5d7 2023-12-01)`.
* * *
CC: @peter-scholtens

Reduce the TTL from 3 secs to 2.5 secs in the cascading drop example

---

.ci_extras/pin-crate-vers-msrv.sh

Pin the version of `cargo-platform` to v0.1.5.

Fix the CI for the MSRV 1.65.0. (Moka v0.12.x)

---

.ci_extras/pin-crate-vers-msrv.sh

Pin the version of `cargo-platform` to v0.1.5.

Fix the CI for the MSRV 1.65.0. (Moka v0.11.x)

---

examples/README.md
examples/eviction_listener_sync.rs

Remove the following comment from the `eviction_listener_sync` example because it was addressed by #348 for `v0.12.2`.
```rust
cache.insert(&2, "twice".to_string());
// Due to race condition spilled over maybe evicted twice by cause
// Replaced and Size.
cache.insert(&2, "two".to_string());
```
**v0.12.1**
```console
$ cargo run --example eviction_listener -F sync
Evicted (2,"twice") because Replaced
Wake up!
Evicted (2,"twice") because Size
Evicted (2,"two") because Size
Evicted (0,"zero") because Expired
Evicted (1,"one") because Expired
Evicted (3,"three") because Explicit
Evicted (4,"four") because Explicit
Evicted (5,"five") because Explicit
Cache structure removed.
Exit program.
```
**v0.12.2**
```console
$ cargo run --example eviction_listener -F sync
Evicted (2,"twice") because …
```

Remove a comment about a race condition from the eviction listener example

---

.vscode/settings.json
CHANGELOG.md
Cargo.toml
README.md
examples/README.md
examples/append_value_async.rs
examples/append_value_sync.rs
examples/bounded_counter_async.rs
examples/bounded_counter_sync.rs
examples/counter_async.rs
examples/counter_sync.rs
examples/try_append_value_async.rs
examples/try_append_value_sync.rs
src/common/entry.rs
src/future.rs
src/future/base_cache.rs
src/future/cache.rs
src/future/entry_selector.rs
src/future/value_initializer.rs
src/lib.rs
src/ops.rs
src/sync.rs
src/sync/cache.rs
src/sync/entry_selector.rs
src/sync/segment.rs
src/sync/value_initializer.rs
src/sync_base/base_cache.rs

Fixes #227, #353.
This PR adds compute family-methods to the `entry` API. They take a closure to insert, update, or remove a value for a key depending on the current cached value.
Also bumps the version to `v0.12.3`.
```rust
/// Upsert (update or insert) the cached entry.
pub async fn and_upsert_with<F, Fut>(self, f: F) -> Entry<K, V>
where
F: FnOnce(Option<Entry<K, V>>) -> Fut,
Fut: Future<Output = V>;
/// Upsert, remove or nop (no-operation) on the cached entry.
pub async fn and_compute_with<F, Fut>(self, f: F) -> compute::CompResult<K, V>)
where
F: FnOnce(Option<Entry<K, V>>) -> Fut,
Fut: Future<Output = compute::Op<V>>;
/// When Ok(Op), upsert, remove or nop (no-operation) on the cached entry.
/// Otherwise return Err(E)
pub async fn and_try_compute_with<F, Fut, E>(
self,
f: F,
) -> …
```

Add the upsert and compute methods for modifying a cached entry

---

src/future/cache.rs
src/future/value_initializer.rs
src/sync/cache.rs
src/sync/segment.rs
src/sync/value_initializer.rs

Relates to #329, a bug in `v0.12.0` that was fixed for `v0.12.1`.
Update the tests for `get_with`, `and_compute_with`, etc. to ensure the internal waiter map is empty at the end.

Compute API - Update the tests to ensure the internal waiter map is empty at the end

---

CHANGELOG.md
Cargo.toml

Raise the version requirement of the `quanta` from `>=0.11.0, <0.12.0` to `>=0.12.2, <0.13.0` to avoid under-measuring the elapsed time on Apple silicon Macs.
- Due to this under-measurement, cached entries expire sightly later than expected on macOS arm64.
- For more details, see https://github.com/metrics-rs/quanta/issues/96.

Raise the minimum version of the `quanta` to `v0.12.2`

---

src/future/base_cache.rs
src/future/cache.rs
src/sync/cache.rs
src/sync_base/base_cache.rs

Fixes #383.
This PR ensures `crossbeam-epoch` to run GC (run the `deferred_fn`s in the global bag) when dropping a `moka` cache. This should help the entries, who are currently or previously in the cache, to be dropped.
We have been struggling this `crossbeam-epoch` spec for years. I added a comment to [our notes about this issue](https://github.com/orgs/moka-rs/projects/1?pane=issue&itemId=1314133).

Ensure `crossbeam-epoch` to run GC when dropping a cache

---

.github/workflows/CI.yml
.github/workflows/CIQuantaDisabled.yml
.github/workflows/LinuxCrossCompileTest.yml
src/sync/cache.rs

Run a flaky test `ensure_gc_runs_when_dropping_cache` for `sync::Cache` separately from other tests to avoid interference from other tests running in parallel.
The test was added by #384 to mitigate #383.

CI: Stabilize `ensure_gc_runs_when_dropping_cache` test for `sync::Cache`

---

CHANGELOG.md
src/future/entry_selector.rs

Prepare for v0.12.4 release

---

.github/workflows/Audit.yml
.github/workflows/CI.yml
.github/workflows/CIQuantaDisabled.yml
.github/workflows/Kani.yml
.github/workflows/Lints.yml
.github/workflows/LinuxCrossCompileTest.yml
.github/workflows/Miri.yml
.github/workflows/Skeptic.yml

Add `skip-duplicate-actions@v5` action to skip duplicate GitHub Actions in a pull request.

CI: Skip duplicate GitHub Actions (v0.12.x)

---

.github/workflows/Audit.yml
.github/workflows/CI.yml
.github/workflows/CIQuantaDisabled.yml
.github/workflows/Kani.yml
.github/workflows/Lints.yml
.github/workflows/Miri.yml
.github/workflows/Skeptic.yml

- Remove `actions-rs` GitHub Actions from the CI, except Clippy lint:
- Replace `actions-rs/toolchain@v1` with `dtolnay/rust-toolchain@master`.
- Remove `actions-rs/cargo@v1` and use simple `run` action (e.g. `run: cargo test ...`).
- Replace `actions-rs/audit-check@v1` with `rustsec/audit-check@v1`
- Upgrade `model-checking/kani-github-action` from `v0.28` to `v1.0`.

CI: Remove `actions-rs` GH Actions from the CI where possible (v0.12.x)

---

.github/workflows/Audit.yml
.github/workflows/CI.yml
.github/workflows/CIQuantaDisabled.yml
.github/workflows/Kani.yml
.github/workflows/Lints.yml
.github/workflows/Miri.yml
.github/workflows/Skeptic.yml

- Remove `actions-rs` GitHub Actions from the CI, except Clippy lint:
- Replace `actions-rs/toolchain@v1` with `dtolnay/rust-toolchain@master`.
- Remove `actions-rs/cargo@v1` and use simple `run` action (e.g. `run: cargo test ...`).
- Replace `actions-rs/audit-check@v1` with `rustsec/audit-check@v1`
- Upgrade `model-checking/kani-github-action` from `v0.28` to `v1.0`.

CI: Remove actions-rs GH Actions from the CI where possible (v0.11.x)

---

.ci_extras/pin-crate-vers-msrv.sh
.ci_extras/pin-crate-vers-nightly.sh
.github/workflows/Audit.yml
.github/workflows/CI.yml
.github/workflows/CIQuantaDisabled.yml
.github/workflows/Lints.yml
.github/workflows/LinuxCrossCompileTest.yml
.github/workflows/Miri.yml
.github/workflows/Skeptic.yml

- Add `skip-duplicate-actions@v5` action to skip duplicate GitHub Actions in a pull request.
- Add `fail-fast: false` to CI and CIQuantaDisabled jobs.
- Fix the CI for nightly + minimal crate versions by pining the following crate:
- `proc-macro2@v1.0.63`
- Fix the CI for the MSRV 1.60.0 by pining the following crates:
- `aho-corasick@v1.0.5`
- `bytecount@v0.6.3`
- `cargo-platform@v0.1.5`
- `crossbeam-epoch@v0.9.15`
- `memchr@v2.5.0`
- `regex-automata@v0.3.7`
- `regex@v1.9.4`
- `value-bag@v1.4.1`

CI: Skip duplicate GitHub Actions (v0.10.x)

---

.github/workflows/Audit.yml
.github/workflows/CI.yml
.github/workflows/CIQuantaDisabled.yml
.github/workflows/Lints.yml
.github/workflows/Miri.yml
.github/workflows/Skeptic.yml

- Remove `actions-rs` GitHub Actions from the CI, except Clippy lint:
- Replace `actions-rs/toolchain@v1` with `dtolnay/rust-toolchain@master`.
- Remove `actions-rs/cargo@v1` and use simple `run` action (e.g. `run: cargo test ...`).
- Replace `actions-rs/audit-check@v1` with `rustsec/audit-check@v1`
- Upgrade `model-checking/kani-github-action` from `v0.28` to `v1.0`.

CI: Remove actions-rs GH Actions from the CI where possible (v0.10.x)

---

.github/workflows/Audit.yml
.github/workflows/CI.yml
.github/workflows/CIQuantaDisabled.yml
.github/workflows/Lints.yml
.github/workflows/Miri.yml
.github/workflows/Skeptic.yml

- Remove `actions-rs` GitHub Actions from the CI, except Clippy lint:
- Replace `actions-rs/toolchain@v1` with `dtolnay/rust-toolchain@master`.
- Remove `actions-rs/cargo@v1` and use simple `run` action (e.g. `run: cargo test ...`).
- Replace `actions-rs/audit-check@v1` with `rustsec/audit-check@v1`
- Upgrade `model-checking/kani-github-action` from `v0.28` to `v1.0`.

CI: Remove actions-rs GH Actions from the CI where possible (v0.9.x)

---

.ci_extras/pin-crate-vers-msrv.sh
.ci_extras/pin-crate-vers-nightly.sh
.github/workflows/Lints.yml
.github/workflows/LinuxCrossCompileTest.yml
.github/workflows/Skeptic.yml
.github/workflows/Trybuild.yml
.vscode/settings.json
Cargo.toml
README.md
build.rs
src/common/timer_wheel.rs
src/future/base_cache.rs
src/future/cache.rs
src/lib.rs
src/policy.rs
src/sync/cache.rs
src/sync/segment.rs
src/sync_base/base_cache.rs
tests/skeptic.rs

- Update the doc tests on the `README.md` by replacing Skeptic with a regular `cargo test` command.
- Rename a CI job `Skeptic` to `Trybuild`.
- Fix the CI for nightly + minimal crate versions by pinning `ahash` to v0.8.7.
- Fix beta Clippy warnings.
- clippy 0.1.77 (f2048098a1c 2024-02-09)
- Fix beta compiler warnings.
- rustc 1.77.0-beta.2 (f2048098a 2024-02-09)
- Replace `actions-rs/clippy-check` with a regular GHA `run` command.
- Disable the `fail-fast` flag for the `Lints` and `Trybuild` jobs.

CI: Fix the CI (remove Skeptic etc.) for v0.12.x

---

README.md
examples/reinsert_expired_entries_sync.rs
examples/size_aware_eviction_sync.rs
src/common.rs
src/future/cache.rs
src/sync/cache.rs

This PR fixes Clippy warnings for `moka` v0.12.x.
- clippy 0.1.78 (4147533e05e 2024-03-27)
**NOTE**: Miri test is failing now. It will be tracked by #414.

Fix Clippy warnings (v0.12.x)

---

CHANGELOG.md
Cargo.toml
src/future/base_cache.rs
src/future/cache.rs
src/future/housekeeper.rs

Fixes #412.
This PR prevents the async runtime's schedulers from going into infinite busy loops in an internal `schedule_write_op` method when there are pending `run_pending_tasks` calls on the `future::Cache`.
- This bug was introduced in `v0.12.0` when the background threads were removed from `future::Cache`.
- This bug can occur when `run_pending_task` method is called by user code while cache is receiving a high number of concurrent cache write operations such as `insert`, `get_with` or `invalidate`.
- When it occurs, the `schedule_write_op` method will be spinning in a busy loop forever, causing high CPU usage and  all other async tasks to be starved..
The fix is to replace a `async_lock::RwLock` used in `schedule_write_op` method with an event notification mechanism provided by the …

Prevent pending `run_pending_tasks` of `future::Cache` from causing busy loop in `schedule_write_op` 

---

.ci_extras/pin-crate-vers-kani.sh
.github/workflows/Kani.yml

Fixes #418.
As of April 16, 2024, the latest version `0.49.0` of Kani verifier uses Rust `nightly-2024-03-29`, which cannot compile `proc-macro2@1.0.80`, causing a CI job to tail.
To address the issue, a new version of Kani will be released soon (https://github.com/model-checking/kani/pull/3144). But for now, we workaround the issue by pining some crate versions to older versions.
This PR does the followings when running GitHub CI for Kani verifier:
- Pin `proc-macro2` to `1.0.79`.
- Pin `syn` to `2.0.58`.
- Pinning (downgrading) the `proc-macro2` version requires downgrading `syn`.

CI: Pin `syn` and `proc-macro2` versions for `kani@v0.49.0`

---

CHANGELOG.md
Cargo.toml
src/common.rs
src/common/concurrent/constants.rs
src/common/concurrent/housekeeper.rs
src/future/base_cache.rs
src/future/builder.rs
src/future/cache.rs
src/future/housekeeper.rs
src/sync/builder.rs
src/sync/cache.rs
src/sync/segment.rs
src/sync_base/base_cache.rs

Fixes #408.
This PR ensures that a single call to `run_pending_tasks` to evict as many entries as possible from the cache.
- Disable the batch limits when the eviction listener is not set to the cache.
- So single `run_pending_tasks` call should remove all the entries that can be evicted from the cache.
- Add a hard-coded maintenance task timeout duration.
- When the eviction listener is set, `run_pending_tasks` should stop (return) after the timeout duration is elapsed.
- This is a safe-guard to prevent the maintenance task from running long time when the user provided a slow eviction listener.
- In older versions, the batch size was used to limit the time spent on the maintenance task.
- Note that `run_pending_tasks` checks the timeout only after processing a batch of entries, so …

Make a single call to `run_pending_tasks` to evict as many entries as possible from the cache

---

.ci_extras/pin-crate-vers-kani.sh

Related to:
- #419
Kani verifier `0.50.0` has been released. It uses Rust `nightyl-2024-04-15` so `proc-macro2@1.0.80` and newer should compile with it. This pull request unpins `syn` and `proc-macro2` versions for the CI job for Kani verifier.

CI: Unpin `syn` and `proc-macro2` versions as a new version `0.50.0` of `kani` is released

---

src/future/cache.rs

* remove unused imports
* add feature time to tokio, since the example uses tokio::time
* do cache.run_pending_tasks() before emitting the entry count so that it's accurate

docs: fix per-entry expiration policy documentation

---

.codecov.yml
.github/workflows/Codecov.yml

This PR adds a GitHub Actions job called "Codecov", which does the followings:
- Measure the code coverage on `cargo test`s with `cargo-llvm-cov`.
- Upload the report to codecov.io.

CI: codecov.io - Measure the code coverage with `cargo-llvm-cov` and upload the report to codecov.io

---

Cargo.toml
README.md

Remove the `js` feature.
The `js` feature is experimental and it is actually broken (will not compile). Moka currently does not support Wasm and WASI targets.
Fixes #423.

Remove an experimental `js` feature

---

.cirrus.yml

We use Cirrus CI for testing Moka on real Arm64 machine. However, it takes very long time (about 25 minutes) to complete.
Change Cirrus CI job to be manually triggered, and set up a cron schedule for it. (I hope a manually triggered job can be automatically triggered by cron, but it is not clear on [the doc](https://cirrus-ci.org/guide/writing-tasks/#cron-builds))

CI: Run Cirrus CI only by cron

---

CHANGELOG.md
Cargo.toml
src/future/entry_selector.rs

- Bump the version to `v0.12.8`.

Prepare for v0.12.8 release

---

.ci_extras/pin-crate-vers-msrv.sh

- Pin `cc` to `v1.0.105` when testing the MSRV.

CI: Fix the CI for the MSRV 1.65

---

Cargo.toml

Fixes #427.
This pull request changes `once_cell` crate optional. After applying this change, `once_cell` is used by `moka` only when the followings:
- development build (e.g. `cargo test`).
- `unstable-debug-counters` feature is enabled.
```console
$ cargo tree -i once_cell -F future,sync
once_cell v1.19.0
├── ahash v0.8.11
│   [dev-dependencies]
│   └── moka v0.12.8 ( ... /moka)
├── async-global-executor v2.4.1
│   └── async-std v1.12.0
│       [dev-dependencies]
│       └── moka v0.12.8 ( ... /moka)
├── async-std v1.12.0 (*)
├── quanta v0.12.3
│   └── moka v0.12.8 ( ... /moka)
├── reqwest v0.11.27
│   [dev-dependencies]
│   └── moka v0.12.8 ( ... /moka)
└── tracing-core v0.1.32
└── tracing v0.1.40
├── async-io v2.3.3
│   └── async-global-executor v2.4.1 (*)
├── h2 v0.3.26
│   ├── hyper …
```

Make `once_cell` dependency optional

---

.ci_extras/pin-crate-vers-msrv.sh
src/common/frequency_sketch.rs

- Fix a Clippy warning
- clippy 0.1.81 (6c199c89c72 2024-08-15)
- Fix the CI for the MSRV 1.65.0.
- Pin `tokio` version to `1.38.1`.

Fix CI: Fix a Clippy warning and pin tokio version for the MSRV

---

Cargo.toml
src/future/base_cache.rs
src/future/cache.rs
src/future/housekeeper.rs
src/future/invalidator.rs
src/future/value_initializer.rs
src/sync/cache.rs
src/sync/value_initializer.rs
src/sync_base/base_cache.rs
src/sync_base/invalidator.rs

I originally just found a redundant `Arc::clone` within `GetOrInsert::insert`.
But then I discovered that `GetOrInsert` only has a single implementor and is thus unnecessary indirection.
The similar thing was true for `GetOrRemoveEntry` and `InnerSync`, so I removed those as well. One reason they might have existed was using a trait for code encapsulation, as removing them resulted in a bit more `pub(crate)` visibility, and a bunch more trait bounds all over the place.
However, in particular `#[async_trait]` usage was allocating `Box<dyn Future>` and using dynamic dispatch at runtime. Now that overhead is avoided and the compiler should be able to produce better code.

Remove needless traits along with `async-trait` usage

---

src/common/deque.rs

The test `common::deque::basics` contains several lines that look like this:
```
assert!(std::ptr::eq(head_d, unsafe { node1_ptr.as_ref() }));
```
What is happening is that we assert that `head_c`, a reference, is equal by-address to `node1_ptr`, a `NonNull<_>`. However, the way we do this is by creating a reference, instead of using `as_ptr`.
The current way has several downsides:
* It requires an `unsafe` block. Comparing pointer addresses is safe so this should be unnecessary.
* **It is unsound**, at least under [Tree Borrows](https://www.ralfj.de/blog/2023/06/02/tree-borrows.html) rules. The references created there violate the uniqueness of references/Boxes created internally in the `Deque`, which trips the `Deque` later when it tries to use these internally-held references.
* It is …

Stop creating references unnecessarily to compare pointers by-address

---

.github/workflows/Miri.yml

Our CI runs `miri` on the following internal modules, which contain a bunch of `unsafe` codes.
- `deque`
- `timer_wheel`
And we have only used `miri`'s stacked borrows model to detect pointer aliasing violations.
This pull request adds `miri` tests using tree borrows model so that our CI will detect the problems like the one reported by #452.
https://github.com/moka-rs/moka/actions/runs/10545853093/job/29216602204

CI: Run `miri` using tree borrows in addition to the existing stacked borrows

---

.ci_extras/pin-crate-vers-msrv.sh
.github/workflows/Kani.yml
Cargo.toml
build.rs

- Pin Kani verifier to `v0.54.0` to avoid out of memory errors with `v0.55.0`.
- Pin `tokio-util` version to `0.7.11` to fix the CI for the MSRV `1.65.0`.
- Move the `check-cfg` lint stuff from the build script to `Cargo.toml`.

Fix the CI: 2024-09-15 v0.12.x

---

.ci_extras/pin-crate-vers-nightly.sh
src/cht/iter.rs
src/cht/map/bucket.rs
src/cht/map/bucket_array_ref.rs
src/common/deque.rs
src/common/timer_wheel.rs
src/future.rs
src/future/key_lock.rs
src/future/value_initializer.rs
src/sync/cache.rs
src/sync_base/iter.rs
src/sync_base/key_lock.rs

- Fix beta Clippy warnings
- clippy 0.1.83 (f41c7ed9889 2024-10-31)
- Fix the CI for nightly + minimal crate versions
- Unpin the `proc-macro2` version.
- This fixes #461

Fix Clippy warnings and fix the CI for the minimal crate versions

---

src/future/cache.rs
src/future/entry_selector.rs
src/future/value_initializer.rs

Issue: #433 
It will only evaluate one closure for a certain entry, and other closures will be canceled, returning `CompResult::Unchanged`.
Add `ValueInitializer::post_init_for_try_compute_with_if_nobody_else`. 
Add `Cache::try_compute_if_nobody_else_with_hash_and_fun`. 
Add `RefKeyEntrySelector::and_try_compute_if_nobody_else`.

Support and_try_compute_if_nobody_else

---

src/common/concurrent.rs

- target_has_atomic was stablized in v1.60.0, https://doc.rust-lang.org/beta/releases.html#version-1600-2022-04-07
fix #465

Enable atomic64 only when target supports AtomicU64

---

.ci_extras/pin-crate-vers-msrv.sh
.ci_extras/remove-examples-msrv.sh
.devcontainer/ensure-rust-toolchains-installed.sh
.github/workflows/CI.yml
.github/workflows/CIQuantaDisabled.yml
CHANGELOG.md
Cargo.toml
README.md
src/lib.rs

Update the Minimum Supported Rust Version (MSRV) from 1.66 to 1.70. 
- Rust 1.70.0 was released on  June 1, 2023.
- `quanta@v0.12.4` requires Rust 1.70.0 or later.

Raise the MSRV from 1.70

---

CHANGELOG.md
Cargo.toml
README.md

- Bump the version to `v0.12.9`.
- Update the `CHANGELOG.md`.
- Update the `README.md` and some comments in the `Cargo.toml` for #466.

Prepare for `v0.12.9` release (1/2)

---

src/future/entry_selector.rs

This is for following up #460:
- `#460` added `and_try_compute_if_nobody_else` method to `moka::future::RefKeyEntrySelector`.
- This PR adds the same method to `moka::future::OwnedKeyEntrySelector`.

Add `and_try_compute_if_nobody_else` to `future::OwnedKeyEntrySelector`

---

src/future/base_cache.rs
src/sync_base/base_cache.rs

Fixes #472.
This PR should avoid occasional panic in an internal `base_cache::Clocks::to_std_instant` method by using zero `Duration` if `checked_duration_since` method fails.
I could not figure out why the specific call of `checked_duration_since` method can fail. I might have overlooked something in `moka`'s code, or maybe `quanta::Instant` can return not a monotonically increasing time on some CPUs?

Avoid panic in an internal `base_cache::Clocks::to_std_instant` method

---

CHANGELOG.md
README.md
src/future/cache.rs
src/lib.rs
src/sync/cache.rs
src/sync/segment.rs

Fixes #464.
- Remove leftover mentions of background threads from `invalidate_all` and `invalidate_entries_if` methods of all cache implementations.
- Add the following chapters to the crate top level doc page:
- Cache Policies
- Implementation Details, with explanations about the channels and maintenance tasks.

Documentation: Remove leftover mentions of background threads

---

.github/workflows/CI.yml
.github/workflows/CIArm64.yml
.github/workflows/CIQuantaDisabled.yml
.github/workflows/Codecov.yml
.github/workflows/LinuxCrossCompileTest.yml
CHANGELOG.md
Cargo.toml
README.md
src/common/concurrent.rs
src/common/concurrent/atomic_time/atomic_time.rs
src/common/concurrent/entry_info.rs

Fixes #462, #41.
- Add `portable-atomic` crate for the platforms where `AtomicU64` is not available.
- The crate feature `atomic64` no longer has any effect but we will keep it for now for backward compatibility.
- It will be removed in `v0.13.0` release.

Add `portable-atomic` crate for the platforms where `AtomicU64` is not available

---

.github/workflows/CI.yml
.github/workflows/CIArm64.yml
.github/workflows/CIQuantaEnabled.yml
.github/workflows/Codecov.yml
CHANGELOG.md
Cargo.toml

This PR _disables_ the `quanta` feature by default.
If it is manually enabled, `quanta::Instant` will be used for some performance critical operations in the cache instead of `std::time::Instant`.
The `quanta` crate is a high performance time measurement library and will be great for some use cases such as collecting performance metrics. `moka` used to use `quanta::Instant` all over the place by default. However, `quanta` is not very good for tracking cache entry expiration times because the time measurement can drift over time and it may not be monotonic on some specific hardware (#472). Therefore, using `std::time::Instant` is more appropriate for tracking enty expiration times.
As of `v0.12.10`, the `quanta` feature will not make any noticeable performance difference, but in the future …

Disable the `quanta` feature by default

---

README.md
src/lib.rs

The release date of Rust 1.70.0: https://releases.rs/docs/1.70.0/

Fix typos in the docs about the release date of Rust 1.70.0

---

src/common/frequency_sketch.rs

`clippy 0.1.85 (e30eefff41 2025-01-08)`

Fix a Clippy warning (Rust 1.85 beta)

---

.github/workflows/Loom.yml
src/common/time/clock.rs

Workaround for incorrect compilation of test code when using Rust 1.84.0 for Linux ARMv7 target

---

LICENSE-APACHE
LICENSE-MIT
README.md

- Put the troubleshooting section back in the README, with some rewritten content:
- When I released `v0.12.10`, I removed the troubleshooting section because the problems listed in that section should not occur in `v0.12.10` or later.
- However, I realized that users with older versions may still see the README in this repository, so it is worth keeping the section.
- Remove the FOSSA badge from the README.
- The FOSSA license scan no longer works for some reason.
- Update the copyright year in the LICENSE files.

Put the troubleshooting section back in the README

---

Cargo.toml
examples/README.md
examples/jittered_expiry_policy_sync.rs

- Add the `jittered_expiry_policy_sync` example.
- Add the `rand` crate to the development dependencies.
Fixes #453

Add the `jittered_expiry_policy` example

---

.ci_extras/remove-examples-msrv.sh
src/sync/cache.rs
src/sync/segment.rs

Documentation: Remove the leftover mentions of the `sync` method

---

CHANGELOG.md
Cargo.toml
src/cht/segment.rs
src/future/base_cache.rs
src/future/cache.rs
src/future/entry_selector.rs
src/future/value_initializer.rs
src/lib.rs
src/sync/cache.rs
src/sync/entry_selector.rs
src/sync/segment.rs
src/sync/value_initializer.rs
src/sync_base/base_cache.rs

Support the `Equivalent` trait from the [equivalent crate](https://crates.io/crates/equivalent) for the cache key type `K`. Replace all usages of the trait bound `K: Borrow<Q>` with `Q: Equivalent<K>`.
For example,
**Before**
```rust
pub fn get<Q>(&self, key: &Q) -> Option<V>
where
K: Borrow<Q>,
Q: Hash + Eq + ?Sized,
```
**After**
```rust
pub fn get<Q>(&self, key: &Q) -> Option<V>
where
Q: Equivalent<K> + Hash + ?Sized,
```
https://github.com/indexmap-rs/equivalent/blob/master/README.md
> These traits are not used by the maps in the standard library, but they may add more flexibility in third-party map implementations, especially in situations where a strict `K: Borrow<Q>` relationship is not available.
- Add the [equivalent crate](https://crates.io/crates/equivalent) to the …

Support `Equivalent` trait for the cache key type `K`

---

Cargo.toml

The `loom` dependency is only used for testing and should therefore be a `dev-dependency`. At present, this pulls in an old version `windows` for us which I'd like to get rid of in our dependency tree:
```
❯ cargo tree -i -p windows@0.58.0 --target all
windows v0.58.0
└── generator v0.8.4
└── loom v0.7.2
└── moka v0.12.10
└── firezone-gateway v1.4.7 (/home/thomas/src/github.com/firezone/firezone/rust/gateway)
```
Resolves: #501

Switch loom to a dev-dependency

---

src/future/cache.rs
src/sync/cache.rs
src/sync/segment.rs

Just randomly ran into the todo comment and I realized the clippy warning is no longer there as soon as I wanted to investigate its safety. So maybe time to remove it and close #54?

chore: remove clippy ignore that no longer applies

---

Cargo.toml
src/common/error.rs
src/sync/segment.rs

We were only using thiserror in 2 places, and one of them was in tests. Our usage was also very minimal (no use of the #[from] directive, etc.), so I think it makes more sense to just manually implement Error for these limited uses.
It's hard to see the impact here because we also don't check-in Cargo.lock, but locally running a cargo tree, I see 5 fewer lines of dependencies.
I went down this path because while auditing an unrelated project I maintain, I noticed that we were pulling in 2 copies of thiserror because moka required version 1, but the other project was pulling in version 2. I opened #506 to address that, but that doesn't help any projects out there who are using version 1. Sometimes crates add dedicated version feature flags like thiserror_v1 and thiserror_v2 or something, …

Replace thiserror usage with manual impl

---

.github/workflows/Kani.yml
src/common/concurrent/arc.rs

- Fix Kani test by upgrading Ubuntu from 20.04 to the latest LTS
- Fix a Clippy warning (Rust 1.87 beta)
- `clippy 0.1.87 (af91af44eb 2025-05-07)`

CI: Fix Kani and Clippy tests

---

CHANGELOG.md
Cargo.toml
tests/entry_api_sync.rs

Fixes #503. ([RUSTSEC-2024-0436](https://rustsec.org/advisories/RUSTSEC-2024-0436.html))

Remove unmaintained `paste` crate from the dev-dependencies

---

Cargo.toml

This allows the tests to be built with the latest version of `reqwest`. I confirmed that `cargo test -F sync,future` still passes.

Update reqwest dev-dependency from 0.11 to 0.12

---

src/common/time/clock.rs

remove redundant word in comment

chore: remove redundant word in comment
