README.md, src/future/cache.rs
=> Fix the examples in the docs: Replace futures crate with futures-util crate

src/future/value_initializer.rs, src/sync/base_cache.rs, src/sync/value_initializer.rs
This will reduce the chance of issue #34 occurring.
=> Increase the num segments of the waiters hash table from 16 to 64

CHANGELOG.md, README.md
Update the CHANGELOG and README.
=> Prepare for v0.8.4 release

CHANGELOG.md, README.md, src/future/cache.rs, src/sync/cache.rs, src/sync/segment.rs
* Perhaps, add goals/non-goals?
* Recommend quick_cache crate for simpler use cases.
=> Prepare for v0.9.5 release (part 2)

src/future/cache.rs, src/sync/cache.rs, src/sync/segment.rs
- Add `optionally_get_with_by_ref` and `try_get_with_by_ref` to `sync::SegmentedCache`.
- Remove (comment out) `get_with_if_by_ref` method from `sync` and `future` caches.
=> Add 'by_ref' api (part 2)

CHANGELOG.md, Cargo.toml, README.md, src/future/builder.rs, src/future/cache.rs
- Merge `maint-09` branch, which has `v0.9.7` tag, into the `master` branch.
- Bump the version to `v0.10.0`.
=> Merge `maint-09` branch into `master` branch

CHANGELOG.md, README.md, src/lib.rs
Update the README and CHANGELOG.
=> Prepare for v0.10.0

CHANGELOG.md, Cargo.toml, README.md, src/common/deque.rs, src/sync_base/base_cache.rs, src/unsync/cache.rs
Back-port the following fix to v0.10.3:
- #259 (for v0.11.0)
=> Backport #259 to v0.10.3

src/future/base_cache.rs, src/future/cache.rs, src/sync/cache.rs, src/sync_base/base_cache.rs
Add a missing key-level lock to `invalidate` method.
=> Remove the thread pool from `future::Cache` (follow up)

README.md
=> typo in weblink

CHANGELOG.md
=> Prepare for v0.12.1 release

src/common/concurrent/deques.rs
Does this pattern make more sense?  Wasn't certain, so made a separate PR
=> A slightly better panics

src/future/builder.rs, src/sync/builder.rs
clippy 0.1.75 (782883f6097 2023-11-12)
=> Fix Clippy v0.1.75 warnings (Moka v0.12.x)

CHANGELOG.md
=> Prepare for `v0.12.2` release

.cirrus.yml, Cargo.toml
=> CI: Reenable CirrusCI

src/common/timer_wheel.rs
Fixes #414.
This PR fixes a Stacked Borrow violation in the test code of the `timer_wheel` module.
=> Fix Miri error (Stacked Borrow violation) in the test code of the timer wheel

Cargo.toml
This PR resolves https://github.com/moka-rs/moka/issues/425
=> Pin triomphe to keep the MSRV

README.md
The original algorithm approximated CLOCK-pro, but deviated over time. Now that S3-FIFO has been published, it's actually much closer to that.
=> Update QuickCache table in README.md

CHANGELOG.md
Update the change log for #472.
=> Update the change log (#472)

src/lib.rs
Clippy Beta
```
clippy 0.1.86 (f0cb410305 2025-02-17)
```
=> Fix a Clippy warning
